In [1]:
import os
import pandas as pd

In [2]:
path = "../data/folketinget_data/"

In [3]:
files = os.listdir(path)

In [4]:
print(files)

['Afstemning.json', 'Afstemningstype.json', 'Aktoer.json', 'AktoerAktoer.json', 'AktoerAktoerRolle.json', 'Aktoertype.json', 'Aktstykke.json', 'Almdel.json', 'Dagsordenspunkt.json', 'DagsordenspunktDokument.json', 'DagsordenspunktSag.json', 'Debat.json', 'Dokument.json', 'Dokumentkategori.json', 'Dokumentstatus.json', 'Dokumenttype.json', 'Fil.json', 'folketinget_data.csv', 'folketinget_data_latest.csv', 'Forslag.json', 'KolloneBeskrivelse.json', 'Moede.json', 'MoedeAktoer.json', 'Moedestatus.json', 'Moedetype.json', 'Omtryk.json', 'Periode.json', 'Sag.json', 'SagAktoer.json', 'SagAktoerRolle.json', 'SagDokument.json', 'SagDokumentRolle.json', 'Sagskategori.json', 'Sagsstatus.json', 'Sagstrin.json', 'SagstrinAktoer.json', 'SagstrinAktoerRolle.json', 'SagstrinDokument.json', 'Sagstrinsstatus.json', 'Sagstrinstype.json', 'Sagstype.json', 'Stemme.json', 'Stemmetype.json']

In [5]:
len(files)

43

In [41]:
'Afstemning.json', 'Afstemningstype.json'

('Afstemning.json', 'Afstemningstype.json')

In [42]:
afstemning = pd.read_csv(path+files[0])

In [43]:
afstemning

,id,nummer,konklusion,vedtaget,kommentar,mødeid,typeid,sagstrinid,opdateringsdato
0,1,411,"Vedtaget\n\n108 stemmer for forslaget (V, S, D...",True,NaN,17,2,NaN,2014-09-09T09:05:59.653
1,2,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,18,1,4849.0,2014-09-09T09:25:05.717
2,3,1,"Vedtaget\n\n59 stemmer for forslaget (S, RV, S...",True,NaN,41,3,17351.0,2018-01-24T16:46:33.99
3,4,7,"Vedtaget\n\n72 stemmer for forslaget (S, DF, R...",True,NaN,156,1,18370.0,2018-01-25T10:25:25.64
4,5,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,18,1,4849.0,2017-08-10T12:57:52.27
...,...,...,...,...,...,...,...,...,...
8295,8372,747,"Forslaget blev forkastet. For stemte 29 (DF, S...",False,NaN,11746,4,228579.0,2021-08-27T10:47:23.203
8296,8373,748,"Forslaget blev forkastet. For stemte 20 (SF, E...",False,NaN,11746,4,228579.0,2021-08-27T10:47:23.487
8297,8374,749,"Forslaget blev forkastet. For stemte 31 (DF, S...",False,NaN,11746,4,228579.0,2021-08-27T10:47:23.847
8298,8375,751,"Forslaget blev vedtaget. For stemte 71 (S, V, ...",True,NaN,11747,1,228581.0,2021-08-27T12:10:30.65
8299,8376,2,"Forslaget blev vedtaget. For stemte 57 (S, SF,...",True,Ved en fejl er Brian Bressendorff registreret ...,11807,3,228905.0,2021-10-08T00:39:48.32

In [44]:
afstemnings_type = pd.read_csv(path+files[1])

In [45]:
afstemnings_type

   id                    type          opdateringsdato
0   1      Endelig vedtagelse  2014-08-06T14:40:50.207
1   2      Udvalgsindstilling  2014-08-06T14:40:50.207
2   3  Forslag til vedtagelse  2014-08-06T14:40:50.207
3   4         Ændringsforslag  2014-08-06T14:40:50.207

In [46]:
afstemning.merge(afstemnings_type, how="left", left_on="typeid", right_on="id", ).drop('id_y', axis=1).rename(columns={"id_x":"id"})

,id,nummer,konklusion,vedtaget,kommentar,mødeid,typeid,sagstrinid,opdateringsdato_x,type,opdateringsdato_y
0,1,411,"Vedtaget\n\n108 stemmer for forslaget (V, S, D...",True,NaN,17,2,NaN,2014-09-09T09:05:59.653,Udvalgsindstilling,2014-08-06T14:40:50.207
1,2,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,18,1,4849.0,2014-09-09T09:25:05.717,Endelig vedtagelse,2014-08-06T14:40:50.207
2,3,1,"Vedtaget\n\n59 stemmer for forslaget (S, RV, S...",True,NaN,41,3,17351.0,2018-01-24T16:46:33.99,Forslag til vedtagelse,2014-08-06T14:40:50.207
3,4,7,"Vedtaget\n\n72 stemmer for forslaget (S, DF, R...",True,NaN,156,1,18370.0,2018-01-25T10:25:25.64,Endelig vedtagelse,2014-08-06T14:40:50.207
4,5,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,18,1,4849.0,2017-08-10T12:57:52.27,Endelig vedtagelse,2014-08-06T14:40:50.207
...,...,...,...,...,...,...,...,...,...,...,...
8295,8372,747,"Forslaget blev forkastet. For stemte 29 (DF, S...",False,NaN,11746,4,228579.0,2021-08-27T10:47:23.203,Ændringsforslag,2014-08-06T14:40:50.207
8296,8373,748,"Forslaget blev forkastet. For stemte 20 (SF, E...",False,NaN,11746,4,228579.0,2021-08-27T10:47:23.487,Ændringsforslag,2014-08-06T14:40:50.207
8297,8374,749,"Forslaget blev forkastet. For stemte 31 (DF, S...",False,NaN,11746,4,228579.0,2021-08-27T10:47:23.847,Ændringsforslag,2014-08-06T14:40:50.207
8298,8375,751,"Forslaget blev vedtaget. For stemte 71 (S, V, ...",True,NaN,11747,1,228581.0,2021-08-27T12:10:30.65,Endelig vedtagelse,2014-08-06T14:40:50.207
8299,8376,2,"Forslaget blev vedtaget. For stemte 57 (S, SF,...",True,Ved en fejl er Brian Bressendorff registreret ...,11807,3,228905.0,2021-10-08T00:39:48.32,Forslag til vedtagelse,2014-08-06T14:40:50.207

In [47]:
'Aktoer.json', 'AktoerAktoer.json', 'AktoerAktoerRolle.json', 'Aktoertype.json'

('Aktoer.json',
 'AktoerAktoer.json',
 'AktoerAktoerRolle.json',
 'Aktoertype.json')

In [48]:
aktøer = pd.read_csv(path+files[2])
aktøeraktøer = pd.read_csv(path+files[3])
aktøeraktøerrolle = pd.read_csv(path+files[4])
aktøertype = pd.read_csv(path+files[5])

In [49]:
aktøer

,id,typeid,gruppenavnkort,navn,fornavn,efternavn,biografi,periodeid,opdateringsdato,startdato,slutdato
0,1,3,FIU,Finansudvalget,NaN,NaN,NaN,32.0,2021-10-11T19:22:08.997,2013-10-01T00:00:00,2014-10-07T00:00:00
1,2,1,NaN,Finansministeriet,NaN,NaN,NaN,NaN,2020-10-06T14:29:01.507,2001-11-27T00:00:00,NaN
2,3,2,finansminister,finansministeren,NaN,NaN,NaN,NaN,2021-10-11T19:19:31.763,2019-06-27T00:00:00,NaN
3,4,2,økonomi- og indenrigsminister,økonomi- og indenrigsministeren,NaN,NaN,NaN,NaN,2021-10-11T19:19:42.783,2014-09-02T00:00:00,2015-06-28T00:00:00
4,5,5,NaN,Frank Aaen,Frank,Aaen,<member><url>/medlemmer/mf/f/frank-aaen</url><...,NaN,2021-09-30T09:48:38.46,2018-10-01T00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...
17200,19931,12,NaN,Hanne Vad Sørensen,Hanne Vad,Sørensen,NaN,NaN,2021-10-05T10:57:49.753,NaN,NaN
17201,19933,4,UFG,Uden for folketingsgrupperne - Lars Løkke Rasm...,NaN,NaN,NaN,155.0,2021-10-11T19:17:31.46,2021-10-05T00:00:00,2022-10-04T00:00:00
17202,19935,12,NaN,Erik Sminge Bundgaard,NaN,NaN,NaN,NaN,2021-10-07T13:43:48.073,NaN,NaN
17203,19936,13,SDG,2030-netværket,NaN,NaN,NaN,155.0,2021-10-11T19:22:32.83,2021-10-05T00:00:00,2022-10-04T00:00:00
17204,19937,13,SRSR,Folketingets Tværpolitiske netværk for seksuel...,NaN,NaN,NaN,155.0,2021-10-11T19:22:29.157,2021-10-05T00:00:00,2022-10-04T00:00:00

In [50]:
aktøeraktøer

,id,fraaktørid,tilaktørid,startdato,slutdato,opdateringsdato,rolleid
0,3,1,264,2013-10-02T00:00:00,NaN,2014-08-11T13:51:38.45,15
1,4,1,201,2014-06-16T00:00:00,NaN,2015-06-30T15:35:00.61,15
2,5,1,5,2014-06-19T00:00:00,NaN,2015-06-30T15:35:00.643,15
3,7,1,173,2013-10-02T00:00:00,NaN,2014-08-11T13:51:38.45,15
4,8,1,98,2013-10-02T00:00:00,NaN,2014-08-11T13:51:38.45,15
...,...,...,...,...,...,...,...
124261,28264723,213,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,16
124262,28264724,139,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,14
124263,28264725,274,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,13
124264,28264726,275,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,2
124265,28264727,15963,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,4

In [51]:
aktøeraktøerrolle

    id                 rolle          opdateringsdato
0    1        1. næstformand   2015-05-29T14:49:17.54
1    2      udvalgsassistent   2015-04-22T12:53:24.92
2    3    Tidligere minister  2014-08-06T14:43:17.187
3    4      udvalgssekretær2  2014-08-06T14:43:17.187
4    5        3. næstformand  2014-08-06T14:43:17.187
5    6    orlov med vederlag  2015-02-10T14:45:59.597
6    7  folketingets formand  2014-08-06T14:43:17.187
7    8              Minister  2015-07-06T13:36:24.093
8    9        2. næstformand  2014-08-06T14:43:17.187
9   10         stedfortræder  2015-08-13T10:24:26.357
10  11        4. næstformand  2014-08-06T14:43:17.187
11  12   orlov uden vederlag  2014-10-16T21:09:23.957
12  13       udvalgssekretær  2015-04-23T15:53:56.433
13  14           næstformand  2015-07-07T11:42:46.047
14  15                medlem  2015-06-03T13:28:02.543
15  16               formand  2015-04-24T14:39:50.027
16  17   delegationssekretær   2014-09-11T15:43:08.39
17  18            Observatør  2014-08-06T14:43:17.187
18  19     udvalgsassistent2  2014-10-08T14:32:23.837
19  20         Ministertitel  2014-09-11T18:18:25.843
20  21  delegationsassistent  2014-09-11T17:04:59.773
21  22       minister, ej MF  2014-10-07T14:13:15.187
22  23        nævnsassistent  2015-06-02T14:03:15.693
23  24         nævnssekretær  2014-10-08T14:04:02.757

In [52]:
aktøeraktøer.merge(aktøeraktøerrolle, how="left", left_on="rolleid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

,id,fraaktørid,tilaktørid,startdato,slutdato,opdateringsdato_x,rolleid,rolle,opdateringsdato_y
0,3,1,264,2013-10-02T00:00:00,NaN,2014-08-11T13:51:38.45,15,medlem,2015-06-03T13:28:02.543
1,4,1,201,2014-06-16T00:00:00,NaN,2015-06-30T15:35:00.61,15,medlem,2015-06-03T13:28:02.543
2,5,1,5,2014-06-19T00:00:00,NaN,2015-06-30T15:35:00.643,15,medlem,2015-06-03T13:28:02.543
3,7,1,173,2013-10-02T00:00:00,NaN,2014-08-11T13:51:38.45,15,medlem,2015-06-03T13:28:02.543
4,8,1,98,2013-10-02T00:00:00,NaN,2014-08-11T13:51:38.45,15,medlem,2015-06-03T13:28:02.543
...,...,...,...,...,...,...,...,...,...
124261,28264723,213,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,16,formand,2015-04-24T14:39:50.027
124262,28264724,139,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,14,næstformand,2015-07-07T11:42:46.047
124263,28264725,274,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,13,udvalgssekretær,2015-04-23T15:53:56.433
124264,28264726,275,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,2,udvalgsassistent,2015-04-22T12:53:24.92
124265,28264727,15963,19897,2021-10-06T00:00:00,NaN,2021-10-12T10:45:39.9,4,udvalgssekretær2,2014-08-06T14:43:17.187

In [53]:
aktøertype

    id                       type          opdateringsdato
0    1             Ministerområde   2015-08-13T11:22:10.49
1    2              Ministertitel  2015-08-13T10:47:17.533
2    3                     Udvalg  2015-07-03T12:30:41.907
3    4           Folketingsgruppe  2015-05-11T13:25:06.573
4    5                     Person  2015-07-23T14:08:13.347
5    6                     Gruppe  2014-08-06T14:43:17.187
6    7               Anden gruppe  2014-08-06T14:43:17.187
7    8                Ministerium  2014-08-06T14:43:17.187
8    9                 Kommission  2015-06-02T14:57:33.623
9   10               Organisation  2015-07-15T13:11:55.147
10  11  Parlamentarisk forsamling  2015-06-03T13:28:02.543
11  12               Privatperson   2015-07-09T13:39:05.05
12  13       Tværpolitisk netværk  2020-10-05T16:15:21.907

In [54]:
aktøer.merge(aktøertype, how="left", left_on="typeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

,id,typeid,gruppenavnkort,navn,fornavn,efternavn,biografi,periodeid,opdateringsdato_x,startdato,slutdato,type,opdateringsdato_y
0,1,3,FIU,Finansudvalget,NaN,NaN,NaN,32.0,2021-10-11T19:22:08.997,2013-10-01T00:00:00,2014-10-07T00:00:00,Udvalg,2015-07-03T12:30:41.907
1,2,1,NaN,Finansministeriet,NaN,NaN,NaN,NaN,2020-10-06T14:29:01.507,2001-11-27T00:00:00,NaN,Ministerområde,2015-08-13T11:22:10.49
2,3,2,finansminister,finansministeren,NaN,NaN,NaN,NaN,2021-10-11T19:19:31.763,2019-06-27T00:00:00,NaN,Ministertitel,2015-08-13T10:47:17.533
3,4,2,økonomi- og indenrigsminister,økonomi- og indenrigsministeren,NaN,NaN,NaN,NaN,2021-10-11T19:19:42.783,2014-09-02T00:00:00,2015-06-28T00:00:00,Ministertitel,2015-08-13T10:47:17.533
4,5,5,NaN,Frank Aaen,Frank,Aaen,<member><url>/medlemmer/mf/f/frank-aaen</url><...,NaN,2021-09-30T09:48:38.46,2018-10-01T00:00:00,NaN,Person,2015-07-23T14:08:13.347
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17200,19931,12,NaN,Hanne Vad Sørensen,Hanne Vad,Sørensen,NaN,NaN,2021-10-05T10:57:49.753,NaN,NaN,Privatperson,2015-07-09T13:39:05.05
17201,19933,4,UFG,Uden for folketingsgrupperne - Lars Løkke Rasm...,NaN,NaN,NaN,155.0,2021-10-11T19:17:31.46,2021-10-05T00:00:00,2022-10-04T00:00:00,Folketingsgruppe,2015-05-11T13:25:06.573
17202,19935,12,NaN,Erik Sminge Bundgaard,NaN,NaN,NaN,NaN,2021-10-07T13:43:48.073,NaN,NaN,Privatperson,2015-07-09T13:39:05.05
17203,19936,13,SDG,2030-netværket,NaN,NaN,NaN,155.0,2021-10-11T19:22:32.83,2021-10-05T00:00:00,2022-10-04T00:00:00,Tværpolitisk netværk,2020-10-05T16:15:21.907
17204,19937,13,SRSR,Folketingets Tværpolitiske netværk for seksuel...,NaN,NaN,NaN,155.0,2021-10-11T19:22:29.157,2021-10-05T00:00:00,2022-10-04T00:00:00,Tværpolitisk netværk,2020-10-05T16:15:21.907

In [55]:
'Aktstykke.json', 'Almdel.json',

('Aktstykke.json', 'Almdel.json')

In [56]:
aktstykke = pd.read_csv(path+files[6])

In [57]:
aktstykke.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4199 entries, 0 to 4198
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      4199 non-null   int64
 1   typeid                  4199 non-null   int64
 2   kategoriid              4199 non-null   int64
 3   statusid                4199 non-null   int64
 4   titel                   4199 non-null   object
 5   titelkort               4199 non-null   object
 6   offentlighedskode       4199 non-null   object
 7   nummer                  4199 non-null   object
 8   nummerprefix            4199 non-null   object
 9   nummernumerisk          4199 non-null   int64
 10  nummerpostfix           283 non-null    object
 11  resume                  4160 non-null   object
 12  afstemningskonklusion   3622 non-null   object
 13  periodeid               4199 non-null   int64
 14  afgørelsesresultatkode  0 non-null      float64
 15  baggrundsmateriale      0 non-null      float64
 16  opdateringsdato         4199 non-null   object
 17  statsbudgetsag          4199 non-null   bool
 18  begrundelse             0 non-null      float64
 19  paragrafnummer          0 non-null      float64
 20  paragraf                0 non-null      float64
 21  afgørelsesdato          0 non-null      float64
 22  afgørelse               0 non-null      float64
 23  rådsmødedato            0 non-null      float64
 24  lovnummer               3664 non-null   object
 25  lovnummerdato           3663 non-null   object
 26  retsinformationsurl     0 non-null      float64
 27  fremsatundersagid       0 non-null      float64
 28  deltundersagid          286 non-null    float64
dtypes: bool(1), float64(11), int64(6), object(11)
memory usage: 922.8+ KB

In [58]:
aktstykke.head()

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,paragrafnummer,paragraf,afgørelsesdato,afgørelse,rådsmødedato,lovnummer,lovnummerdato,retsinformationsurl,fremsatundersagid,deltundersagid
0,66,3,13,11,Forslag til lov om tillægsbevilling for finans...,Om tillægsbevillingsloven for finansåret 2013.,O,L 105,L,105,...,NaN,NaN,NaN,NaN,NaN,1,2014-03-18T00:00:00,NaN,NaN,NaN
1,68,3,13,11,Forslag til lov om ændring af lov om Det Centr...,Om tildeling af nyt personnummer i særlige til...,O,L 110,L,110,...,NaN,NaN,NaN,NaN,NaN,311,2014-03-29T00:00:00,NaN,NaN,NaN
2,69,3,13,11,Forslag til lov om Danmarks Innovationsfond.,Om Danmarks Innovationsfond.,O,L 107,L,107,...,NaN,NaN,NaN,NaN,NaN,306,2014-03-29T00:00:00,NaN,NaN,NaN
3,70,3,13,11,Forslag til lov om ændring af lov om forskning...,Om konsekvensændringer som følge af lov om Dan...,O,L 109,L,109,...,NaN,NaN,NaN,NaN,NaN,310,2014-03-29T00:00:00,NaN,NaN,NaN
4,71,3,13,11,Forslag til lov om ændring af lov om teknologi...,Om konsekvensændringer som følge af lov om Dan...,O,L 108,L,108,...,NaN,NaN,NaN,NaN,NaN,309,2014-03-29T00:00:00,NaN,NaN,NaN

In [59]:
almdel = pd.read_csv(path+files[7])

In [60]:
almdel.columns

Index(['id', 'typeid', 'kategoriid', 'statusid', 'titel', 'titelkort',
       'offentlighedskode', 'nummer', 'nummerprefix', 'nummernumerisk',
       'nummerpostfix', 'resume', 'afstemningskonklusion', 'periodeid',
       'afgørelsesresultatkode', 'baggrundsmateriale', 'opdateringsdato',
       'statsbudgetsag', 'begrundelse', 'paragrafnummer', 'paragraf',
       'afgørelsesdato', 'afgørelse', 'rådsmødedato', 'lovnummer',
       'lovnummerdato', 'retsinformationsurl', 'fremsatundersagid',
       'deltundersagid'],
      dtype='object')

In [61]:
almdel.head()

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,paragrafnummer,paragraf,afgørelsesdato,afgørelse,rådsmødedato,lovnummer,lovnummerdato,retsinformationsurl,fremsatundersagid,deltundersagid
0,7337,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7338,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7339,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7344,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,35738,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
'Dagsordenspunkt.json', 'DagsordenspunktDokument.json'

('Dagsordenspunkt.json', 'DagsordenspunktDokument.json')

In [63]:
dagsordenspunkt = pd.read_csv(path+files[8])
dagsordenspunkt

,id,kørebemærkning,titel,kommentar,nummer,forhandlingskode,forhandling,superid,sagstrinid,mødeid,offentlighedskode,opdateringsdato
0,1,NaN,Drøftelse og afgivelse af tilsynets årlige ber...,NaN,1,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
1,2,NaN,Drøftelse af svar fra Region Sjælland vedr. ti...,NaN,2,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
2,3,NaN,Drøftelse af evalueringen af ordningen med tvu...,NaN,3,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
3,4,NaN,Svar vedr. hvilke regler der gælder for tvangs...,NaN,4,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
4,5,NaN,"Svar vedr. en nærmere redegørelse for, hvilke ...",NaN,5,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
...,...,...,...,...,...,...,...,...,...,...,...,...
26028,71888,NaN,Eventuelt.,NaN,4,NaN,NaN,NaN,NaN,11979,O,2021-10-11T16:19:42.723
26029,71889,NaN,Modtagelse af deputation fra:,NaN,2,NaN,NaN,NaN,NaN,11942,O,2021-10-12T09:21:29.947
26030,71890,NaN,Tivoliforeningen vedr. støtte til de omrejsend...,NaN,a,NaN,NaN,NaN,230103.0,11942,O,2021-10-12T09:21:29.96
26031,71891,NaN,Modtagelse af deputation fra:,NaN,1,NaN,NaN,NaN,NaN,11945,O,2021-10-12T10:04:38.157
26032,71892,NaN,Præsteforeningen m.fl. vedr. nedlæggelse af Pe...,NaN,a,NaN,NaN,NaN,230104.0,11945,O,2021-10-12T10:04:38.157

In [64]:
dagsordenspunkt.head()

,id,kørebemærkning,titel,kommentar,nummer,forhandlingskode,forhandling,superid,sagstrinid,mødeid,offentlighedskode,opdateringsdato
0,1,NaN,Drøftelse og afgivelse af tilsynets årlige ber...,NaN,1,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
1,2,NaN,Drøftelse af svar fra Region Sjælland vedr. ti...,NaN,2,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
2,3,NaN,Drøftelse af evalueringen af ordningen med tvu...,NaN,3,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
3,4,NaN,Svar vedr. hvilke regler der gælder for tvangs...,NaN,4,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
4,5,NaN,"Svar vedr. en nærmere redegørelse for, hvilke ...",NaN,5,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447

In [65]:
dagsordenspunktdokument = pd.read_csv(path+files[9])

In [66]:
dagsordenspunktdokument.head()

   id  dokumentid  dagsordenspunktid note          opdateringsdato
0   2       11612                 67  NaN   2014-09-10T13:17:24.08
1   3       10777                 69  NaN   2014-09-10T14:50:00.71
2   4       10778                 69  NaN   2014-09-10T14:50:00.71
3   6       25419                 83  NaN  2014-09-11T13:01:38.527
4   7       25619                 74  NaN   2014-09-12T10:31:42.19

In [67]:
dagsorden = dagsordenspunkt.merge(dagsordenspunktdokument, how="left", left_on="id", right_on="dagsordenspunktid").drop("id_y", axis=1).rename(columns={"id_x": "id"})

In [68]:
dagsorden

,id,kørebemærkning,titel,kommentar,nummer,forhandlingskode,forhandling,superid,sagstrinid,mødeid,offentlighedskode,opdateringsdato_x,dokumentid,dagsordenspunktid,note,opdateringsdato_y
0,1,NaN,Drøftelse og afgivelse af tilsynets årlige ber...,NaN,1,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447,NaN,NaN,NaN,NaN
1,2,NaN,Drøftelse af svar fra Region Sjælland vedr. ti...,NaN,2,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447,NaN,NaN,NaN,NaN
2,3,NaN,Drøftelse af evalueringen af ordningen med tvu...,NaN,3,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447,11466.0,3.0,NaN,2014-11-12T09:11:53.447
3,4,NaN,Svar vedr. hvilke regler der gælder for tvangs...,NaN,4,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447,11467.0,4.0,NaN,2014-11-12T09:11:53.447
4,5,NaN,"Svar vedr. en nærmere redegørelse for, hvilke ...",NaN,5,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447,11468.0,5.0,NaN,2014-11-12T09:11:53.447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39638,71888,NaN,Eventuelt.,NaN,4,NaN,NaN,NaN,NaN,11979,O,2021-10-11T16:19:42.723,NaN,NaN,NaN,NaN
39639,71889,NaN,Modtagelse af deputation fra:,NaN,2,NaN,NaN,NaN,NaN,11942,O,2021-10-12T09:21:29.947,NaN,NaN,NaN,NaN
39640,71890,NaN,Tivoliforeningen vedr. støtte til de omrejsend...,NaN,a,NaN,NaN,NaN,230103.0,11942,O,2021-10-12T09:21:29.96,NaN,NaN,NaN,NaN
39641,71891,NaN,Modtagelse af deputation fra:,NaN,1,NaN,NaN,NaN,NaN,11945,O,2021-10-12T10:04:38.157,NaN,NaN,NaN,NaN
39642,71892,NaN,Præsteforeningen m.fl. vedr. nedlæggelse af Pe...,NaN,a,NaN,NaN,NaN,230104.0,11945,O,2021-10-12T10:04:38.157,944164.0,71892.0,NaN,2021-10-12T10:04:38.157

In [69]:
dagsorden.merge(dagsordenspunktsag, how="left", on="dagsordenspunktid").drop("id_y", axis=1).rename(columns={"id_x":"id"})

NameError: name 'dagsordenspunktsag' is not defined

In [70]:
'DagsordenspunktSag.json', 'Debat.json', 'Dokument.json', 'Dokumentkategori.json', 'Dokumentstatus.json', 'Dokumenttype.json'

('DagsordenspunktSag.json',
 'Debat.json',
 'Dokument.json',
 'Dokumentkategori.json',
 'Dokumentstatus.json',
 'Dokumenttype.json')

In [71]:
dagsordenspunktsag = pd.read_csv(path+files[10])

In [72]:
dagsordenspunktsag

         id  dagsordenspunktid  sagid          opdateringsdato
0         3                101   6900  2014-09-16T15:57:33.623
1         4                100    648  2014-09-16T15:57:33.623
2         6                102   6901  2014-09-16T15:57:33.623
3         7                103   6902  2014-09-16T15:57:33.623
4        11               3748   2230  2014-09-19T14:23:57.567
...     ...                ...    ...                      ...
5854  29529              71747  89758  2021-10-12T09:21:29.947
5855  29530              71890  89758   2021-10-12T09:21:29.96
5856  29531              71768  89749   2021-10-12T09:26:28.71
5857  29532              71892  89619  2021-10-12T10:04:38.157
5858  29533              71605  89619  2021-10-12T10:04:38.157

[5859 rows x 4 columns]

In [73]:
debat = pd.read_csv(path+files[11])

In [74]:
debat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2417 entries, 0 to 2416
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2417 non-null   int64
 1   typeid                  2417 non-null   int64
 2   kategoriid              576 non-null    float64
 3   statusid                2417 non-null   int64
 4   titel                   2417 non-null   object
 5   titelkort               2417 non-null   object
 6   offentlighedskode       2417 non-null   object
 7   nummer                  2415 non-null   object
 8   nummerprefix            325 non-null    object
 9   nummernumerisk          325 non-null    float64
 10  nummerpostfix           0 non-null      float64
 11  resume                  42 non-null     object
 12  afstemningskonklusion   0 non-null      float64
 13  periodeid               2417 non-null   int64
 14  afgørelsesresultatkode  0 non-null      float64
 15  baggrundsmateriale      0 non-null      float64
 16  opdateringsdato         2417 non-null   object
 17  statsbudgetsag          2417 non-null   bool
 18  begrundelse             0 non-null      float64
 19  paragrafnummer          0 non-null      float64
 20  paragraf                0 non-null      float64
 21  afgørelsesdato          0 non-null      float64
 22  afgørelse               0 non-null      float64
 23  rådsmødedato            1778 non-null   object
 24  lovnummer               0 non-null      float64
 25  lovnummerdato           0 non-null      float64
 26  retsinformationsurl     0 non-null      float64
 27  fremsatundersagid       0 non-null      float64
 28  deltundersagid          0 non-null      float64
dtypes: bool(1), float64(16), int64(4), object(8)
memory usage: 531.2+ KB

In [75]:
dokument = pd.read_csv(path+files[12])

/home/carbon/.conda/envs/flow/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [76]:
dokument.head()

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato,modtagelsesdato,frigivelsesdato,paragraf,paragrafnummer,spørgsmålsordlyd,spørgsmålstitel,spørgsmålsid,procedurenummer,grundnotatstatus,dagsordenudgavenummer,opdateringsdato
0,1,13,36,1,O,Spm. om formuefordelingen fordelt på både indk...,2014-08-08T00:00:00,NaN,2014-08-08T14:57:26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-03-14T09:32:33.387
1,2,16,14,1,O,"Er ministeren enig i vurderingen af, at grønla...",2014-01-02T00:00:00,NaN,2014-01-02T11:36:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:34.047
2,3,17,22,1,O,Svar på spm. nr. S 725: Er ministeren enig i v...,2014-01-09T00:00:00,2014-01-09T00:00:00,2014-01-10T09:26:05,NaN,NaN,NaN,"Er ministeren enig i vurderingen af, at grønla...",2.0,NaN,NaN,NaN,2014-09-30T16:15:46.607
3,4,16,14,1,O,"Hvad agter ministeren at foretage sig, så kost...",2014-01-02T00:00:00,NaN,2014-01-20T10:12:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:32.563
4,5,17,22,1,O,Svar på spm. nr. S 726: Hvad agter ministeren ...,2014-01-08T00:00:00,2014-01-08T00:00:00,2014-01-08T11:02:45,NaN,NaN,NaN,"Hvad agter ministeren at foretage sig, så kost...",4.0,NaN,NaN,NaN,2015-05-29T08:42:54.09

In [77]:
dokumentkategori = pd.read_csv(path+files[13])
dokument_status = pd.read_csv(path+files[14])
dokumenttype = pd.read_csv(path+files[15])

In [78]:
dokumentkategori

    id                      kategori          opdateringsdato
0    1            Beslutningsreferat   2014-09-11T17:44:36.23
1    2              Pressemeddelelse  2014-08-06T14:43:17.187
2    3         Forslag til afgørelse   2014-06-24T15:24:23.66
3    4                       Hvidbog  2014-08-06T14:43:17.187
4    5                   Redegørelse   2014-06-24T15:24:23.66
..  ..                           ...                      ...
78  79               Arbejdsdokument   2015-06-01T15:10:32.86
79  80    Forslag til rammeafgørelse  2015-06-26T10:51:50.327
80  81          Indkommende dokument  2015-09-16T14:19:37.723
81  82  Internt notat med opfølgning  2015-09-16T14:19:37.723
82  83       Godkendelsesindstilling  2015-09-16T14:19:37.723

[83 rows x 3 columns]

In [79]:
dokument_status

   id        status          opdateringsdato
0   1      Endeligt  2015-07-15T09:44:04.857
1   2          Låst  2014-09-27T11:37:32.857
2   3        Omdelt   2014-11-13T10:31:39.22
3   4  Tilbagetaget  2014-09-19T09:03:42.327
4   5    Foreløbigt  2015-09-16T14:19:37.723

In [80]:
dokumenttype

    id                     type          opdateringsdato
0    1              Redegørelse  2015-05-20T13:01:40.133
1    2        Stedfortræderbrev  2014-08-06T14:43:17.187
2    3      Ministerredegørelse  2015-03-04T11:11:40.247
3    4                Aktstykke   2015-07-06T14:27:03.72
4    5             Forespørgsel  2015-03-25T13:39:31.217
5    6                  EU-note  2014-10-06T09:22:10.703
6    7        Fremsættelsestale  2015-03-26T10:06:41.623
7    8                  Referat  2014-08-06T14:43:17.187
8    9       Formandsmeddelelse  2014-08-06T14:43:17.187
9   10                    Notat  2014-09-29T11:26:54.447
10  11   Statsrevisorbemærkning  2014-10-11T01:33:50.333
11  12                    Bilag  2015-05-27T13:57:25.723
12  13                Spørgsmål  2015-05-26T14:37:05.147
13  14       Indstilling til EB  2014-08-06T14:43:17.187
14  15                Beretning  2014-08-06T14:43:17.187
15  16           § 20-spørgsmål  2015-05-21T11:22:00.407
16  17                     Svar  2015-05-26T14:41:14.663
17  18       Kommissionsforslag  2015-06-02T14:09:44.647
18  19               Grundnotat  2014-08-06T14:43:17.187
19  20         Rådsmødedokument  2014-11-27T15:04:27.737
20  21            Forslagstekst  2015-05-19T16:21:19.653
21  22                Dagsorden  2014-09-13T11:21:16.467
22  23                 Tekstdel  2014-10-11T01:33:49.647
23  24          Orlovsansøgning  2014-09-13T14:25:29.433
24  25                  Ugeplan  2015-09-16T14:19:37.723
25  26                    Andet  2014-10-10T18:08:29.227
26  27                Info-note  2014-12-16T15:33:51.913
27  28  Godkendelsesindstilling  2015-09-16T14:19:37.723

In [81]:
dokument = dokument.merge(dokumentkategori, how="left", left_on="kategoriid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [82]:
dokument = dokument.merge(dokument_status, how="left", left_on="statusid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [83]:
dokument = dokument.merge(dokumenttype, how="left", left_on="typeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [84]:
dokument.head()

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato,modtagelsesdato,frigivelsesdato,paragraf,...,procedurenummer,grundnotatstatus,dagsordenudgavenummer,opdateringsdato_x,kategori,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y
0,1,13,36,1,O,Spm. om formuefordelingen fordelt på både indk...,2014-08-08T00:00:00,NaN,2014-08-08T14:57:26,NaN,...,NaN,NaN,NaN,2016-03-14T09:32:33.387,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147
1,2,16,14,1,O,"Er ministeren enig i vurderingen af, at grønla...",2014-01-02T00:00:00,NaN,2014-01-02T11:36:24,NaN,...,NaN,NaN,NaN,2015-05-29T11:11:34.047,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407
2,3,17,22,1,O,Svar på spm. nr. S 725: Er ministeren enig i v...,2014-01-09T00:00:00,2014-01-09T00:00:00,2014-01-10T09:26:05,NaN,...,NaN,NaN,NaN,2014-09-30T16:15:46.607,Endeligt svar,2015-05-26T14:41:14.663,Endeligt,2015-07-15T09:44:04.857,Svar,2015-05-26T14:41:14.663
3,4,16,14,1,O,"Hvad agter ministeren at foretage sig, så kost...",2014-01-02T00:00:00,NaN,2014-01-20T10:12:24,NaN,...,NaN,NaN,NaN,2015-05-29T11:11:32.563,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407
4,5,17,22,1,O,Svar på spm. nr. S 726: Hvad agter ministeren ...,2014-01-08T00:00:00,2014-01-08T00:00:00,2014-01-08T11:02:45,NaN,...,NaN,NaN,NaN,2015-05-29T08:42:54.09,Endeligt svar,2015-05-26T14:41:14.663,Endeligt,2015-07-15T09:44:04.857,Svar,2015-05-26T14:41:14.663

In [85]:
len(dokument)

817425

In [86]:
'Fil.json', 'Forslag.json', 'KolloneBeskrivelse.json'

('Fil.json', 'Forslag.json', 'KolloneBeskrivelse.json')

In [87]:
fil = pd.read_csv(path+files[16])

In [88]:
fil

,id,dokumentid,titel,versionsdato,filurl,opdateringsdato,variantkode,format
0,158,11432,Evaluering af lov om friplejeboliger_endelig v...,2014-09-04T15:44:54,https://www.ft.dk/samling/20131/almdel/BYB/bil...,2020-02-25T10:46:59.49,P,PDF
1,159,11432,Redegørelse for evaluering af friplejeboliglov...,2014-09-04T15:44:55,https://www.ft.dk/samling/20131/almdel/BYB/bil...,2020-02-25T10:46:59.49,P,DOCX
2,160,11432,Redegørelse for evaluering af friplejeboliglov...,2014-09-04T15:44:57,https://www.ft.dk/samling/20131/almdel/BYB/bil...,2020-02-25T10:46:59.49,P,PDF
3,162,11430,EU-note om indførsel af tysk infrastrukturafgi...,2014-09-04T15:49:38,https://www.ft.dk/samling/20131/almdel/TRU/bil...,2020-02-25T10:46:59.487,P,DOCX
4,164,11433,Yderligere Suppl Bemærkninger til L200 - Skatt...,2014-09-04T15:56:54,https://www.ft.dk/samling/20131/lovforslag/L20...,2020-02-25T10:46:59.487,P,DOCX
...,...,...,...,...,...,...,...,...
416827,1629166,944555,Udvalgsspørgsmål.pdf,2021-10-12T16:35:51,https://www.ft.dk/samling/20211/almdel/ufo/spm...,2021-10-12T16:36:55.223,P,PDF
416828,1629177,944559,(20201) FiU L239 - svar på spørgsmål 118,2021-10-12T16:36:00,https://www.ft.dk/samling/20201/lovforslag/l23...,2021-10-12T16:39:00.71,P,DOCX
416829,1629184,944561,FiU L 239 - svar på spørgsmål 112,2021-10-12T16:42:27,https://www.ft.dk/samling/20201/lovforslag/l23...,2021-10-12T16:44:23.427,P,DOCX
416830,1629187,944562,(20201) FIU L 239 - svar på spm. 237.pdf,2021-10-12T16:47:35,https://www.ft.dk/samling/20201/lovforslag/l23...,2021-10-12T16:49:54.153,P,PDF
416831,1629199,944567,Oversendelsesbrev,2021-10-12T17:01:41,https://www.ft.dk/samling/20211/almdel/eru/bil...,2021-10-12T17:03:48.583,P,DOCX

In [89]:
fil_dokument = fil.merge(dokument, how="left", left_on="dokumentid", right_on="id")

In [90]:
forslag = pd.read_csv(path+files[17])

In [91]:
forslag.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3304 entries, 0 to 3303
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      3304 non-null   int64
 1   typeid                  3304 non-null   int64
 2   kategoriid              0 non-null      float64
 3   statusid                3304 non-null   int64
 4   titel                   3304 non-null   object
 5   titelkort               3304 non-null   object
 6   offentlighedskode       3304 non-null   object
 7   nummer                  3304 non-null   object
 8   nummerprefix            3304 non-null   object
 9   nummernumerisk          3304 non-null   int64
 10  nummerpostfix           0 non-null      float64
 11  resume                  13 non-null     object
 12  afstemningskonklusion   0 non-null      float64
 13  periodeid               3304 non-null   int64
 14  afgørelsesresultatkode  3239 non-null   object
 15  baggrundsmateriale      0 non-null      float64
 16  opdateringsdato         3304 non-null   object
 17  statsbudgetsag          3304 non-null   bool
 18  begrundelse             0 non-null      float64
 19  paragrafnummer          3304 non-null   int64
 20  paragraf                3304 non-null   object
 21  afgørelsesdato          3234 non-null   object
 22  afgørelse               3237 non-null   object
 23  rådsmødedato            0 non-null      float64
 24  lovnummer               0 non-null      float64
 25  lovnummerdato           0 non-null      float64
 26  retsinformationsurl     0 non-null      float64
 27  fremsatundersagid       0 non-null      float64
 28  deltundersagid          0 non-null      float64
dtypes: bool(1), float64(11), int64(6), object(11)
memory usage: 726.1+ KB

In [92]:
kolonnebeskrivelse = pd.read_csv(path+files[18])

In [93]:
kolonnebeskrivelse

,id,entitetnavn,kollonenavn,beskrivelse,opdateringsdato
0,0,Afstemning,id,Unik identifikation af Aktør,2015-09-24T12:48:31.82
1,1,Afstemning,kommentar,Afstemningskommentar (ændring af stemmer ved f...,2015-09-24T12:48:31.82
2,2,Afstemning,konklusion,"Afstemningsresultat, hvor der stemmes om et fo...",2015-09-24T12:48:31.82
3,3,Afstemning,mødeid,En afstemning foregår i et møde.,2015-09-24T12:48:31.82
4,4,Afstemning,nummer,"Afstemningsnummer, fortløbende indenfor en per...",2015-09-24T12:48:31.82
...,...,...,...,...,...
219,219,SyncLogger,eksternId,NaN,2015-09-24T12:48:31.82
220,220,SyncLogger,entitet,NaN,2015-09-24T12:48:31.82
221,221,SyncLogger,godkendtdato,NaN,2015-09-24T12:48:31.82
222,222,SyncLogger,id,NaN,2015-09-24T12:48:31.82
223,223,SyncLogger,internId,NaN,2015-09-24T12:48:31.82

In [94]:
'Moede.json', 'MoedeAktoer.json', 'Moedestatus.json', 'Moedetype.json'

('Moede.json', 'MoedeAktoer.json', 'Moedestatus.json', 'Moedetype.json')

In [95]:
møde = pd.read_csv(path+files[19])
mødeaktøer = pd.read_csv(path+files[20])
mødestatus = pd.read_csv(path+files[21])
mødetype = pd.read_csv(path+files[22])

In [96]:
møde

,id,titel,lokale,nummer,dagsordenurl,starttidsbemærkning,offentlighedskode,dato,statusid,typeid,periodeid,opdateringsdato
0,1,Møde i REU den 8/9-14,2-080,NaN,NaN,11.00,O,2014-09-08T11:00:00,2,2,32,2014-11-12T09:14:16.883
1,2,MIU - Ekspertmøde om EU´s affaldsdirektiv,1-133,NaN,NaN,Kl. 10.30,O,2014-09-25T10:30:00,2,2,32,2014-09-30T13:02:16.317
2,3,MIU - Dep. - Åbent samråd (AL),2-080,NaN,NaN,Kl. 10.00,O,2014-09-18T10:00:00,2,2,32,2014-11-12T09:14:58.773
3,4,Møde den 9/9-14,1-008,NaN,NaN,13.15,O,2014-09-09T13:15:00,2,2,32,2014-11-12T09:11:53.447
4,5,Møde i REU den 9/9-14,S-092,NaN,NaN,15.00,O,2014-09-09T15:00:00,2,2,32,2014-09-19T14:46:22.96
...,...,...,...,...,...,...,...,...,...,...,...,...
9683,11978,Social- og Ældreudvalget - dep.,S-092,NaN,NaN,NaN,O,2021-10-28T13:00:00,1,2,155,2021-10-12T10:02:32.807
9684,11979,Sundhedsudvalget,2-011,NaN,NaN,kl. 14.00,O,2021-10-26T14:00:00,1,2,155,2021-10-11T16:19:42.723
9685,11980,Sundhedsudvalget,2-011,NaN,NaN,kl. 15.00,O,2021-10-28T15:00:00,1,2,155,2021-10-12T14:07:18.1
9686,11981,Granskningsudvalget,2-011,NaN,NaN,kl. 9.30,O,2021-10-15T09:30:00,1,2,155,2021-10-12T14:33:32.783
9687,11982,Beskæftigelsesudvalget,2-011,NaN,NaN,kl. 12.00,O,2021-11-10T12:00:00,1,2,155,2021-10-12T16:29:00.91

In [97]:
mødeaktøer

          id  mødeid  aktørid          opdateringsdato
0          6       6       63  2014-09-05T11:46:31.463
1         15      15        6    2014-09-05T15:52:05.9
2        541     774        6   2014-09-19T14:20:36.44
3        543     777        6  2014-09-19T14:20:39.333
4        544     775        6  2014-09-19T14:20:39.503
...      ...     ...      ...                      ...
8926  101450   11942    19912  2021-10-12T16:05:12.047
8927  101453   11982    19889   2021-10-12T16:29:00.91
8928  101456   11943    19878  2021-10-12T16:47:59.327
8929  101457   11928    19911  2021-10-12T16:55:25.813
8930  101458   11782    19829  2021-10-12T17:02:01.837

[8931 rows x 4 columns]

In [98]:
mødestatus

   id              status          opdateringsdato
0   1  Under forberedelse  2015-07-14T11:59:42.647
1   2             Afholdt  2015-03-27T10:10:52.513
2   3              Aflyst  2014-09-19T14:36:24.413
3   4      Dagsorden låst   2014-10-15T10:27:06.11
4   5               Udsat  2015-01-27T11:59:31.077

In [99]:
mødetype

   id              type          opdateringsdato
0   1      Møde i salen  2015-06-25T13:13:02.187
1   2       Udvalgsmøde   2015-07-03T12:33:40.64
2   3        Andet møde  2014-11-04T12:09:35.093
3   4  ConciergeMeeting    2014-06-24T15:12:59.5
4   5  Statsrevisormøde  2015-11-18T10:41:42.077

In [100]:
møde = møde.merge(mødeaktøer, how="left", left_on="id", right_on="mødeid").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [101]:
møde = møde.merge(mødestatus, how="left", left_on="statusid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [102]:
møde = møde.merge(mødetype, how="left", left_on="typeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [103]:
møde

,id,titel,lokale,nummer,dagsordenurl,starttidsbemærkning,offentlighedskode,dato,statusid,typeid,periodeid,opdateringsdato_x,mødeid,aktørid,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y
0,1,Møde i REU den 8/9-14,2-080,NaN,NaN,11.00,O,2014-09-08T11:00:00,2,2,32,2014-11-12T09:14:16.883,NaN,NaN,NaN,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64
1,2,MIU - Ekspertmøde om EU´s affaldsdirektiv,1-133,NaN,NaN,Kl. 10.30,O,2014-09-25T10:30:00,2,2,32,2014-09-30T13:02:16.317,NaN,NaN,NaN,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64
2,3,MIU - Dep. - Åbent samråd (AL),2-080,NaN,NaN,Kl. 10.00,O,2014-09-18T10:00:00,2,2,32,2014-11-12T09:14:58.773,NaN,NaN,NaN,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64
3,4,Møde den 9/9-14,1-008,NaN,NaN,13.15,O,2014-09-09T13:15:00,2,2,32,2014-11-12T09:11:53.447,NaN,NaN,NaN,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64
4,5,Møde i REU den 9/9-14,S-092,NaN,NaN,15.00,O,2014-09-09T15:00:00,2,2,32,2014-09-19T14:46:22.96,NaN,NaN,NaN,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9685,11978,Social- og Ældreudvalget - dep.,S-092,NaN,NaN,NaN,O,2021-10-28T13:00:00,1,2,155,2021-10-12T10:02:32.807,11978.0,19902.0,2021-10-12T10:02:32.807,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64
9686,11979,Sundhedsudvalget,2-011,NaN,NaN,kl. 14.00,O,2021-10-26T14:00:00,1,2,155,2021-10-11T16:19:42.723,11979.0,19921.0,2021-10-11T16:19:42.723,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64
9687,11980,Sundhedsudvalget,2-011,NaN,NaN,kl. 15.00,O,2021-10-28T15:00:00,1,2,155,2021-10-12T14:07:18.1,11980.0,19921.0,2021-10-12T14:07:18.1,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64
9688,11981,Granskningsudvalget,2-011,NaN,NaN,kl. 9.30,O,2021-10-15T09:30:00,1,2,155,2021-10-12T14:33:32.783,11981.0,19880.0,2021-10-12T14:33:32.783,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64
9689,11982,Beskæftigelsesudvalget,2-011,NaN,NaN,kl. 12.00,O,2021-11-10T12:00:00,1,2,155,2021-10-12T16:29:00.91,11982.0,19889.0,2021-10-12T16:29:00.91,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64

In [104]:
'Omtryk.json', 'Periode.json'

('Omtryk.json', 'Periode.json')

In [105]:
omtryk = pd.read_csv(path+files[23])
periode = pd.read_csv(path+files[24])

In [106]:
omtryk

,id,dokumentid,dato,begrundelse,opdateringsdato
0,1,1,2014-08-11T12:52:54.987,Ændret adressat,2016-03-14T09:32:33.387
1,2,1000,2014-08-07T13:01:08.6,Ændret adressat,2014-08-11T13:36:38.563
2,3,9440,2014-08-12T10:09:16.603,Ændret adressat,2014-08-12T10:09:28.007
3,4,9496,2014-06-03T12:45:08.147,Ændret adressat,2014-08-12T14:01:27.43
4,6,9567,2014-07-25T10:44:02.497,Ændret adressat,2014-08-12T21:58:05.073
...,...,...,...,...,...
10525,13543,937798,2021-10-12T12:46:08,Yderligere bilag tilføjet,2021-10-12T12:46:22.98
10526,13544,944219,2021-10-12T12:49:01.39,Ændret medspørger,2021-10-12T12:49:15.433
10527,13545,944220,2021-10-12T12:50:08.99,Ændret medspørger,2021-10-12T12:50:28.327
10528,13546,943759,2021-10-12T13:31:44.09,Ændret adressat,2021-10-12T13:32:05.017
10529,13547,943760,2021-10-12T13:32:33.767,Ændret adressat,2021-10-12T13:32:50.423

In [107]:
periode

,id,startdato,slutdato,type,kode,titel,opdateringsdato
0,1,1995-01-01T00:00:00,1995-12-31T00:00:00,finans,19951,1995,2014-08-11T12:51:35
1,2,1996-01-01T12:00:00,1996-12-31T12:00:00,finans,19961,1996,2014-08-11T12:51:35
2,3,2002-01-01T00:00:00,2002-12-31T00:00:00,finans,20021,2002,2014-08-11T12:51:35
3,4,2003-01-01T00:00:00,2003-12-31T00:00:00,finans,20031,2003,2014-08-11T12:51:35
4,5,2004-01-01T00:00:00,2004-12-31T00:00:00,finans,20041,2004,2014-08-11T12:51:35
...,...,...,...,...,...,...,...
146,151,2019-10-01T12:00:00,2020-10-06T12:00:00,samling,20191,2019-20,2019-09-09T12:29:48.397
147,152,2020-01-01T12:00:00,2020-12-31T12:00:00,finans,20201,2020,2019-12-18T16:48:20.937
148,153,2020-10-06T12:00:00,2021-10-05T12:00:00,samling,20201,2020-21,2020-10-01T16:07:28.523
149,154,2020-01-01T12:00:00,2021-12-31T12:00:00,finans,20211,2021,2021-03-01T13:00:08.27
150,155,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07

In [108]:
møde = møde.merge(periode, how="left", left_on="periodeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [109]:
møde

,id,titel_x,lokale,nummer,dagsordenurl,starttidsbemærkning,offentlighedskode,dato,statusid,typeid,...,status,opdateringsdato_x,type_x,opdateringsdato_y,startdato,slutdato,type_y,kode,titel_y,opdateringsdato
0,1,Møde i REU den 8/9-14,2-080,NaN,NaN,11.00,O,2014-09-08T11:00:00,2,2,...,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64,2013-10-01T12:00:00,2014-10-01T12:00:00,samling,20131,2013-14,2014-08-11T12:51:35
1,2,MIU - Ekspertmøde om EU´s affaldsdirektiv,1-133,NaN,NaN,Kl. 10.30,O,2014-09-25T10:30:00,2,2,...,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64,2013-10-01T12:00:00,2014-10-01T12:00:00,samling,20131,2013-14,2014-08-11T12:51:35
2,3,MIU - Dep. - Åbent samråd (AL),2-080,NaN,NaN,Kl. 10.00,O,2014-09-18T10:00:00,2,2,...,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64,2013-10-01T12:00:00,2014-10-01T12:00:00,samling,20131,2013-14,2014-08-11T12:51:35
3,4,Møde den 9/9-14,1-008,NaN,NaN,13.15,O,2014-09-09T13:15:00,2,2,...,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64,2013-10-01T12:00:00,2014-10-01T12:00:00,samling,20131,2013-14,2014-08-11T12:51:35
4,5,Møde i REU den 9/9-14,S-092,NaN,NaN,15.00,O,2014-09-09T15:00:00,2,2,...,Afholdt,2015-03-27T10:10:52.513,Udvalgsmøde,2015-07-03T12:33:40.64,2013-10-01T12:00:00,2014-10-01T12:00:00,samling,20131,2013-14,2014-08-11T12:51:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9685,11978,Social- og Ældreudvalget - dep.,S-092,NaN,NaN,NaN,O,2021-10-28T13:00:00,1,2,...,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07
9686,11979,Sundhedsudvalget,2-011,NaN,NaN,kl. 14.00,O,2021-10-26T14:00:00,1,2,...,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07
9687,11980,Sundhedsudvalget,2-011,NaN,NaN,kl. 15.00,O,2021-10-28T15:00:00,1,2,...,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07
9688,11981,Granskningsudvalget,2-011,NaN,NaN,kl. 9.30,O,2021-10-15T09:30:00,1,2,...,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07
9689,11982,Beskæftigelsesudvalget,2-011,NaN,NaN,kl. 12.00,O,2021-11-10T12:00:00,1,2,...,Under forberedelse,2015-07-14T11:59:42.647,Udvalgsmøde,2015-07-03T12:33:40.64,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07

In [110]:
dokument = dokument.merge(omtryk, how="left", left_on="id", right_on="dokumentid").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [111]:
dokument

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato_x,modtagelsesdato,frigivelsesdato,paragraf,...,kategori,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y,dokumentid,dato_y,begrundelse,opdateringsdato
0,1,13,36,1,O,Spm. om formuefordelingen fordelt på både indk...,2014-08-08T00:00:00,NaN,2014-08-08T14:57:26,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,1.0,2014-08-11T12:52:54.987,Ændret adressat,2016-03-14T09:32:33.387
1,2,16,14,1,O,"Er ministeren enig i vurderingen af, at grønla...",2014-01-02T00:00:00,NaN,2014-01-02T11:36:24,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN
2,3,17,22,1,O,Svar på spm. nr. S 725: Er ministeren enig i v...,2014-01-09T00:00:00,2014-01-09T00:00:00,2014-01-10T09:26:05,NaN,...,Endeligt svar,2015-05-26T14:41:14.663,Endeligt,2015-07-15T09:44:04.857,Svar,2015-05-26T14:41:14.663,NaN,NaN,NaN,NaN
3,4,16,14,1,O,"Hvad agter ministeren at foretage sig, så kost...",2014-01-02T00:00:00,NaN,2014-01-20T10:12:24,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN
4,5,17,22,1,O,Svar på spm. nr. S 726: Hvad agter ministeren ...,2014-01-08T00:00:00,2014-01-08T00:00:00,2014-01-08T11:02:45,NaN,...,Endeligt svar,2015-05-26T14:41:14.663,Endeligt,2015-07-15T09:44:04.857,Svar,2015-05-26T14:41:14.663,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818017,949243,13,36,1,O,"Spm., om i hvor mange dobbeltbeskatningsoveren...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T16:51:39,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,NaN,NaN,NaN,NaN
818018,949244,13,36,1,O,"Spm., om at bekræfte, at når Skattestyrelsen i...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T16:53:29,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,NaN,NaN,NaN,NaN
818019,949247,13,36,1,O,"Spm., om en opgørelse for kalenderårene 2018, ...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T16:55:20,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,NaN,NaN,NaN,NaN
818020,949252,16,14,1,O,Vil ministeren redegøre for status på Det arab...,2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T17:34:15,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN
818021,949253,16,14,1,O,"Mener ministeren, at der er en sammenhæng mell...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T17:29:08,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN

In [112]:
'Sag.json', 'SagAktoer.json', 'SagAktoerRolle.json', 'SagDokument.json', 'SagDokumentRolle.json', 'Sagskategori.json', 'Sagsstatus.json', 'Sagstrin.json', 'SagstrinAktoer.json', 'SagstrinAktoerRolle.json', 'SagstrinDokument.json', 'Sagstrinsstatus.json', 'Sagstrinstype.json', 'Sagstype.json'

('Sag.json',
 'SagAktoer.json',
 'SagAktoerRolle.json',
 'SagDokument.json',
 'SagDokumentRolle.json',
 'Sagskategori.json',
 'Sagsstatus.json',
 'Sagstrin.json',
 'SagstrinAktoer.json',
 'SagstrinAktoerRolle.json',
 'SagstrinDokument.json',
 'Sagstrinsstatus.json',
 'Sagstrinstype.json',
 'Sagstype.json')

In [113]:
sag = pd.read_csv(path+files[25])
sagaktøer = pd.read_csv(path+files[26])
sagaktøerrolle = pd.read_csv(path+files[27])
sagdokument = pd.read_csv(path+files[28])
sagdokumentrolle = pd.read_csv(path+files[29])
sagkategori = pd.read_csv(path+files[30])
sagstatus = pd.read_csv(path+files[31])
sagstrin = pd.read_csv(path+files[32])
sagstrinaktøer = pd.read_csv(path+files[33])
sagstrinaktøerrolle = pd.read_csv(path+files[34])
sagstrindokument = pd.read_csv(path+files[35])
sagstrinstatus = pd.read_csv(path+files[36])
sagstrintype = pd.read_csv(path+files[37])
sagstype = pd.read_csv(path+files[38])

In [114]:
dokument

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato_x,modtagelsesdato,frigivelsesdato,paragraf,...,kategori,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y,dokumentid,dato_y,begrundelse,opdateringsdato
0,1,13,36,1,O,Spm. om formuefordelingen fordelt på både indk...,2014-08-08T00:00:00,NaN,2014-08-08T14:57:26,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,1.0,2014-08-11T12:52:54.987,Ændret adressat,2016-03-14T09:32:33.387
1,2,16,14,1,O,"Er ministeren enig i vurderingen af, at grønla...",2014-01-02T00:00:00,NaN,2014-01-02T11:36:24,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN
2,3,17,22,1,O,Svar på spm. nr. S 725: Er ministeren enig i v...,2014-01-09T00:00:00,2014-01-09T00:00:00,2014-01-10T09:26:05,NaN,...,Endeligt svar,2015-05-26T14:41:14.663,Endeligt,2015-07-15T09:44:04.857,Svar,2015-05-26T14:41:14.663,NaN,NaN,NaN,NaN
3,4,16,14,1,O,"Hvad agter ministeren at foretage sig, så kost...",2014-01-02T00:00:00,NaN,2014-01-20T10:12:24,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN
4,5,17,22,1,O,Svar på spm. nr. S 726: Hvad agter ministeren ...,2014-01-08T00:00:00,2014-01-08T00:00:00,2014-01-08T11:02:45,NaN,...,Endeligt svar,2015-05-26T14:41:14.663,Endeligt,2015-07-15T09:44:04.857,Svar,2015-05-26T14:41:14.663,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818017,949243,13,36,1,O,"Spm., om i hvor mange dobbeltbeskatningsoveren...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T16:51:39,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,NaN,NaN,NaN,NaN
818018,949244,13,36,1,O,"Spm., om at bekræfte, at når Skattestyrelsen i...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T16:53:29,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,NaN,NaN,NaN,NaN
818019,949247,13,36,1,O,"Spm., om en opgørelse for kalenderårene 2018, ...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T16:55:20,NaN,...,Udvalgsspørgsmål,2015-05-20T15:05:09.583,Endeligt,2015-07-15T09:44:04.857,Spørgsmål,2015-05-26T14:37:05.147,NaN,NaN,NaN,NaN
818020,949252,16,14,1,O,Vil ministeren redegøre for status på Det arab...,2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T17:34:15,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN
818021,949253,16,14,1,O,"Mener ministeren, at der er en sammenhæng mell...",2021-11-04T00:00:00,2021-11-04T00:00:00,2021-11-04T17:29:08,NaN,...,§ 20-spørgsmål,2015-05-21T11:36:44.877,Endeligt,2015-07-15T09:44:04.857,§ 20-spørgsmål,2015-05-21T11:22:00.407,NaN,NaN,NaN,NaN

In [115]:
sagaktøer

             id  aktørid  sagid          opdateringsdato  rolleid
0          2212      255    370   2014-08-11T13:23:02.27        9
1          2213      256    371   2014-08-11T13:23:02.52        9
2          2221      196    373  2014-08-11T13:23:04.003        9
3         23659      372   4010  2014-08-11T19:19:55.973        9
4         23660      174   4012   2014-08-11T19:19:56.69        9
...         ...      ...    ...                      ...      ...
367894  1564736       11  89797  2021-10-12T16:39:34.943        6
367895  1564737      118  89797  2021-10-12T16:39:34.943       17
367896  1564738    18712  89797  2021-10-12T16:39:34.943       10
367897  1564740    19829  89782   2021-10-12T17:04:30.44       11
367898  1564742    19829  89783  2021-10-12T17:05:16.943       11

[367899 rows x 5 columns]

In [116]:
sag = sag.merge(sagaktøer, how="left", left_on="id", right_on="sagid").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [117]:
sagaktøerrolle

    id                           rolle          opdateringsdato
0    1                           Taler  2014-06-24T15:13:26.853
1    2  Ordfører for forslagsstillerne  2014-06-24T15:13:26.853
2    3           Tidligere henvist til  2014-06-24T15:13:26.853
3    4                              Af  2015-07-15T13:11:55.147
4    5                      Medspørger  2015-05-29T11:39:49.237
5    6                  Ministerområde  2015-07-06T15:03:37.307
6    7                       Privatist  2014-06-24T15:13:26.853
7    8                  Kopi sendt til  2015-01-29T09:32:58.137
8    9                    Relevant for  2015-07-09T13:31:43.287
9   10                         Spørger   2015-06-01T11:33:00.79
10  11                     Henvist til  2015-06-25T14:52:28.353
11  12                        Udsteder  2015-02-12T13:31:30.293
12  13                      Optaget af  2014-06-24T15:13:26.853
13  14                        Minister  2015-08-13T10:24:56.373
14  15                     Forespørger  2015-05-20T18:17:12.463
15  16         Forslagsstiller (priv.)  2015-05-29T16:33:18.817
16  17                             Til  2015-07-09T13:49:36.873
17  18                      Afgivet af  2015-05-20T13:01:40.133
18  19          Forslagsstiller (reg.)  2015-06-08T15:33:53.347
19  20                   Orlovssøgende  2015-09-16T14:19:37.723
20  21                   Stedfortræder  2015-09-16T14:19:37.723
21  22            Statsrevisor inhabil  2015-09-16T14:19:37.723
22  23                     Besvaret af  2015-09-16T14:19:37.723

In [118]:
sag = sag.merge(sagaktøerrolle, how="left", left_on="rolleid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [119]:
sagdokument

,id,sagid,dokumentid,bilagsnummer,frigivelsesdato,opdateringsdato,rolleid
0,21,4496,7913,NaN,2013-10-16T14:54:51,2014-09-16T06:16:53.99,4
1,30,4886,8595,NaN,2013-11-20T13:40:45,2014-09-14T06:18:43.64,4
2,55,4262,7515,NaN,2013-10-01T15:51:19,2014-09-14T03:18:42.27,4
3,84,5063,8896,NaN,2013-12-02T11:05:42,2014-09-14T07:18:11.007,4
4,87,4680,8245,NaN,2013-11-01T10:29:01,2014-09-14T05:19:24.097,4
...,...,...,...,...,...,...,...
536579,1225576,89605,949213,Spørgsmål 129,2021-11-04T00:00:00,2021-11-04T15:49:16.647,4
536580,1225577,89755,949214,Spørgsmål 179,2021-11-04T00:00:00,2021-11-04T15:50:10.537,4
536581,1225578,89755,949215,Spørgsmål 180,2021-11-04T00:00:00,2021-11-04T15:50:45.377,4
536582,1225579,89755,949216,Spørgsmål 181,2021-11-04T00:00:00,2021-11-04T15:51:48.46,4
536583,1225580,89755,949219,Spørgsmål 182,2021-11-04T00:00:00,2021-11-04T15:55:41.23,4

In [120]:
sagdokumentrolle

   id              rolle          opdateringsdato
0   1     Tidl. jour. på  2014-09-19T14:51:24.773
1   2  Parallelomdelt på  2014-10-06T13:54:15.487
2   3        På sagstrin   2015-05-12T14:33:34.01
3   4   Hovedtilknytning  2015-07-15T09:44:04.857
4   5            Se også   2014-09-19T14:24:18.41
5   6           Relation  2014-06-24T15:13:41.907
6   7              Child  2014-06-24T15:13:41.907

In [121]:
sagdokument = sagdokument.merge(sagdokumentrolle, how="left", left_on="rolleid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [122]:
sagkategori

    id                                  kategori          opdateringsdato
0    1                    Beretning af almen art   2014-06-24T15:14:09.67
1    2                                  Alm. del  2015-08-13T10:24:56.373
2    3                                        FT   2014-06-24T15:14:09.67
3    4            Henvendelser uden bilagsnummer   2014-06-24T15:14:09.67
4    5                                   Mødesag   2014-06-24T15:14:09.67
5    6                                Info-noter   2014-06-24T15:14:09.67
6    7                                        US  2015-04-15T12:29:41.997
7    8                       Alm. del §-markeret   2014-06-24T15:14:09.67
8    9                                  EU-noter   2014-06-24T15:14:09.67
9   10    B1 - Privat forslag - 1. (eneste) beh.  2014-10-23T10:49:29.623
10  11                                         S   2015-07-22T14:39:22.49
11  12                            Privat forslag   2014-06-24T15:14:09.67
12  13                          Regeringsforslag  2015-05-27T13:49:30.737
13  14                                        B3   2014-06-24T15:14:09.67
14  15                       B1 - Privat forslag  2015-05-20T18:47:57.483
15  16                                        B2  2015-07-06T15:03:37.307
16  17                     B1 - Regeringsforslag   2014-12-16T18:14:54.87
17  18                                 Beretning   2014-06-24T15:14:09.67
18  19                                     Notat   2014-06-24T15:14:09.67
19  20                        Endelig betænkning   2014-06-24T15:14:09.67
20  21                       Udenrigsanliggender  2015-11-12T10:39:23.383
21  22                                     Miljø  2015-10-15T15:17:48.807
22  23              Retlige og indre anliggender   2015-10-29T13:06:15.79
23  24                        Økonomi og finans   2015-10-29T13:34:46.277
24  25                      Landbrug og fiskeri   2015-10-29T15:27:02.093
25  26                           Konkurrenceevne   2015-11-03T13:34:38.62
26  27                        Det Europæiske Råd  2015-11-04T16:26:55.123
27  28                   Almindelige anliggender   2015-11-05T13:32:42.51
28  29       Uddannelse, ungdom, kultur og sport   2015-11-12T10:34:36.85
29  30    Transport, telekommunikation og energi  2015-11-12T10:37:37.897
30  31  Beskæftigelse, socialpolitik, sundhed ..   2015-11-26T14:17:12.81

In [123]:
sag = sag.merge(sagkategori, how="left", left_on="kategoriid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [124]:
sagstatus

    id                 status          opdateringsdato
0    1              Afsluttet   2014-06-24T15:14:55.25
1    2                Afgivet   2014-06-24T15:14:55.25
2    3              Forkastet   2014-10-09T15:32:11.19
3    4           Tilbagetaget  2015-05-29T13:06:13.967
4    5             Forhandlet   2015-04-08T11:15:51.36
..  ..                    ...                      ...
59  62       Spørgsmål afvist      2017-02-14T09:47:36
60  63              Foreløbig  2018-07-03T16:31:49.877
61  64              Forkastet   2018-07-03T16:31:49.88
62  65                 Afvist   2019-09-05T09:58:02.34
63  66  3. beh. afbrudt/udsat  2021-03-01T16:41:24.267

[64 rows x 3 columns]

In [125]:
sag = sag.merge(sagstatus, how="left", left_on="statusid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [126]:
sagstrin

,id,titel,dato,sagid,typeid,folketingstidendeurl,folketingstidende,folketingstidendesidenummer,statusid,opdateringsdato
0,1,Anmeldelse,2014-01-02T00:00:00,2,1,NaN,NaN,NaN,11,2014-09-30T16:15:46.607
1,2,"Besvarelse, skriftlig",2014-01-09T00:00:00,2,8,NaN,NaN,NaN,12,2014-09-30T16:15:46.607
2,3,Anmeldelse,2014-01-02T00:00:00,3,1,NaN,NaN,NaN,11,2015-05-29T11:11:32.563
3,4,"Besvarelse, skriftlig",2014-01-08T00:00:00,3,8,NaN,NaN,NaN,12,2015-05-29T11:11:32.563
4,8,Anmeldelse,2014-01-03T00:00:00,8,1,NaN,NaN,NaN,11,2015-05-29T11:11:15.453
...,...,...,...,...,...,...,...,...,...,...
189297,230787,Vand i EU’s eksterne relationer – Centralasien,2021-11-12T11:00:00,88498,16,NaN,NaN,NaN,13,2021-11-04T14:55:58.003
189298,230788,Udkast til Rådets afgørelse om undertegnelse p...,2021-11-12T11:00:00,88498,16,NaN,NaN,NaN,13,2021-11-04T14:55:58.113
189299,230789,Genoptagelse af åbent samråd med forsvarsminis...,2021-11-11T10:30:00,89756,46,NaN,NaN,NaN,13,2021-11-04T15:54:36.077
189300,230790,Anmeldelse,2021-11-04T00:00:00,90100,1,NaN,NaN,NaN,11,2021-11-04T17:34:11.687
189301,230792,Anmeldelse,2021-11-04T00:00:00,90101,1,NaN,NaN,NaN,11,2021-11-04T18:03:31.747

In [127]:
sagstrinaktøer

             id  sagstrinid  aktørid          opdateringsdato  rolleid
0             1           1        6  2014-08-11T12:53:19.827        5
1             2           3        6  2014-08-11T12:53:21.013        5
2             6           8        6   2014-08-11T12:53:24.45        5
3             7          10        6   2014-08-11T12:53:25.31        5
4             8          13       19  2014-08-11T12:53:26.777        5
...         ...         ...      ...                      ...      ...
145266  2287209      230258    19829  2021-11-04T15:55:10.577        5
145267  2287210      230584    19829  2021-11-04T16:46:13.513        5
145268  2287211      230790    19854  2021-11-04T17:34:11.687        5
145269  2287212      230777    19854  2021-11-04T18:03:31.697        5
145270  2287213      230792    19854  2021-11-04T18:03:31.747        5

[145271 rows x 5 columns]

In [128]:
sagstrin = sagstrin.merge(sagstrinaktøer, how="left", left_on="id", right_on="sagstrinid").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [129]:
sagstrinaktøerrolle

   id                           rolle          opdateringsdato
0   1      Ordfører for forespørgerne   2014-09-06T07:06:53.78
1   2                        Ordfører  2014-11-05T11:20:07.617
2   3                     Besvaret af   2014-09-06T03:53:43.74
3   4                        Minister  2015-05-12T15:36:48.057
4   5                     Behandles i  2015-05-21T10:12:52.757
5   6  Ordfører for forslagsstillerne   2014-09-06T06:50:18.23
6   7                           Taler  2014-08-11T12:55:05.543
7   8                      Medspørger   2014-06-24T15:15:36.83

In [130]:
sagstrin = sagstrin.merge(sagstrinaktøerrolle, how="left", left_on="rolleid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [131]:
sagstrindokument

           id  sagstrinid  dokumentid          opdateringsdato
0       16399       73983      365065  2015-12-01T12:44:42.937
1       16496       69448      327904  2015-12-03T10:42:43.313
2       16497       67882      365053   2015-12-03T10:45:04.97
3       16498       67921      365092   2015-12-03T10:45:42.97
4       16511      118649      365284  2015-12-03T14:18:17.883
...       ...         ...         ...                      ...
60101  409193      230784      949135  2021-11-04T15:07:43.617
60102  409196      230785      949145      2021-11-04T15:08:52
60103  409199      230786      949145  2021-11-04T15:09:16.783
60104  409200      230581      943762  2021-11-04T15:11:47.387
60105  409201      230581      943767  2021-11-04T15:11:47.387

[60106 rows x 4 columns]

In [132]:
sagstrin = sagstrin.merge(sagstrindokument, how="left", left_on="id", right_on="sagstrinid").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [133]:
sagstrinstatus

      id                              status          opdateringsdato
0      1  Bortfaldet (pga. tid)/tilbagetaget  2014-06-24T15:19:05.423
1      2         Bortfaldet (pga. procedure)  2014-06-24T15:19:05.423
2      3                             Endelig  2014-06-24T15:19:05.423
3      4                             Endelig  2014-10-06T09:23:20.483
4      5           Planlægges til besvarelse  2014-06-24T15:19:05.423
..   ...                                 ...                      ...
278  294                               Udsat  2021-02-19T18:16:35.413
279  295                               Udsat  2021-02-19T18:16:35.417
280  296                               Udsat   2021-02-19T18:16:35.42
281  297                               Udsat   2021-02-19T18:16:35.42
282  298                              Aflyst  2021-03-03T11:19:29.767

[283 rows x 3 columns]

In [134]:
sagstrin = sagstrin.merge(sagstrinstatus, how="left", left_on="statusid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [135]:
sagstrintype

      id                                    type          opdateringsdato
0      1                              Anmeldelse  2015-06-01T09:02:44.147
1      2                               Afgivelse  2014-10-09T10:07:46.277
2      3                             Forhandling  2014-09-08T15:24:06.033
3      4                                  Fremme   2014-06-24T15:16:40.13
4      5                       Forhandlingsoplæg   2014-06-24T15:16:40.13
..   ...                                     ...                      ...
102  103          Spørgetime med statsministeren  2020-10-05T18:22:53.463
103  104  Udvidet spørgetime med statsministeren   2020-10-05T18:22:53.47
104  105                                 Omtrykt  2020-10-05T18:14:32.067
105  106                              Deputation  2020-10-05T18:22:53.463
106  107                         Partilederdebat  2021-03-02T17:23:06.657

[107 rows x 3 columns]

In [136]:
sagstrin = sagstrin.merge(sagstrintype, how="left", left_on="typeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [137]:
sagstrin

,id,titel,dato,sagid,typeid,folketingstidendeurl,folketingstidende,folketingstidendesidenummer,statusid,opdateringsdato_x,...,rolleid,rolle,opdateringsdato_x,sagstrinid_y,dokumentid,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y
0,1,Anmeldelse,2014-01-02T00:00:00,2,1,NaN,NaN,NaN,11,2014-09-30T16:15:46.607,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,Anmeldt,2015-05-21T11:36:44.877,Anmeldelse,2015-06-01T09:02:44.147
1,2,"Besvarelse, skriftlig",2014-01-09T00:00:00,2,8,NaN,NaN,NaN,12,2014-09-30T16:15:46.607,...,NaN,NaN,NaN,NaN,NaN,NaN,Besvaret,2015-05-28T14:31:09.003,"Besvarelse, skriftlig",2015-06-01T09:02:44.147
2,3,Anmeldelse,2014-01-02T00:00:00,3,1,NaN,NaN,NaN,11,2015-05-29T11:11:32.563,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,Anmeldt,2015-05-21T11:36:44.877,Anmeldelse,2015-06-01T09:02:44.147
3,4,"Besvarelse, skriftlig",2014-01-08T00:00:00,3,8,NaN,NaN,NaN,12,2015-05-29T11:11:32.563,...,NaN,NaN,NaN,NaN,NaN,NaN,Besvaret,2015-05-28T14:31:09.003,"Besvarelse, skriftlig",2015-06-01T09:02:44.147
4,8,Anmeldelse,2014-01-03T00:00:00,8,1,NaN,NaN,NaN,11,2015-05-29T11:11:15.453,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,Anmeldt,2015-05-21T11:36:44.877,Anmeldelse,2015-06-01T09:02:44.147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273933,230787,Vand i EU’s eksterne relationer – Centralasien,2021-11-12T11:00:00,88498,16,NaN,NaN,NaN,13,2021-11-04T14:55:58.003,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,På dagsorden,2015-06-16T09:29:31.637,Rådsmødepunkt,2014-09-19T14:42:26.227
273934,230788,Udkast til Rådets afgørelse om undertegnelse p...,2021-11-12T11:00:00,88498,16,NaN,NaN,NaN,13,2021-11-04T14:55:58.113,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,På dagsorden,2015-06-16T09:29:31.637,Rådsmødepunkt,2014-09-19T14:42:26.227
273935,230789,Genoptagelse af åbent samråd med forsvarsminis...,2021-11-11T10:30:00,89756,46,NaN,NaN,NaN,13,2021-11-04T15:54:36.077,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,På dagsorden,2015-06-16T09:29:31.637,Åbent samråd,2014-06-24T15:16:40.13
273936,230790,Anmeldelse,2021-11-04T00:00:00,90100,1,NaN,NaN,NaN,11,2021-11-04T17:34:11.687,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,Anmeldt,2015-05-21T11:36:44.877,Anmeldelse,2015-06-01T09:02:44.147
273937,230792,Anmeldelse,2021-11-04T00:00:00,90101,1,NaN,NaN,NaN,11,2021-11-04T18:03:31.747,...,5.0,Behandles i,2015-05-21T10:12:52.757,NaN,NaN,NaN,Anmeldt,2015-05-21T11:36:44.877,Anmeldelse,2015-06-01T09:02:44.147

In [138]:
sagstype

    id                          type          opdateringsdato
0    1                       UMF-del  2014-06-24T15:16:55.227
1    2                  Forespørgsel  2015-03-20T10:01:13.277
2    3                    Lovforslag  2015-05-27T13:49:30.737
3    4                      Alm. del  2015-08-13T10:24:56.373
4    5            Beslutningsforslag  2015-05-29T16:06:51.047
5    6                      Rådsmøde  2015-05-27T15:04:46.557
6    7            Kommissionsforslag   2014-12-17T10:51:32.77
7    8                     Aktstykke  2015-07-15T13:11:55.147
8    9        Forslag til vedtagelse   2015-05-22T13:12:13.42
9   10                § 20-spørgsmål  2015-05-22T16:22:09.413
10  11                   Redegørelse  2015-04-29T13:44:46.833
11  12  Indkaldelse af stedfortræder  2014-06-24T15:16:55.227
12  13              Statsrevisorerne  2014-06-24T15:16:55.227

In [139]:
sag = sag.merge(sagstype, how="left", left_on="typeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [140]:
sag

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,opdateringsdato_y,rolleid,rolle,opdateringsdato_x,kategori,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y
0,1,4,2.0,8,FIU alm. del,FIU alm. del,O,NaN,NaN,NaN,...,2015-06-23T10:32:14.607,9.0,Relevant for,2015-07-09T13:31:43.287,Alm. del,2015-08-13T10:24:56.373,Igangværende,2015-05-21T11:51:26.38,Alm. del,2015-08-13T10:24:56.373
1,1,4,2.0,8,FIU alm. del,FIU alm. del,O,NaN,NaN,NaN,...,2015-06-23T10:32:14.607,6.0,Ministerområde,2015-07-06T15:03:37.307,Alm. del,2015-08-13T10:24:56.373,Igangværende,2015-05-21T11:51:26.38,Alm. del,2015-08-13T10:24:56.373
2,2,10,11.0,20,"Er ministeren enig i vurderingen af, at grønla...",Om NSA-aflytninger eller aflytninger fra andre...,O,S 725,S,725.0,...,2017-12-05T19:42:22.857,14.0,Minister,2015-08-13T10:24:56.373,S,2015-07-22T14:39:22.49,"Besvaret, endeligt",2015-04-24T10:40:06.503,§ 20-spørgsmål,2015-05-22T16:22:09.413
3,2,10,11.0,20,"Er ministeren enig i vurderingen af, at grønla...",Om NSA-aflytninger eller aflytninger fra andre...,O,S 725,S,725.0,...,2017-12-05T19:42:22.857,9.0,Relevant for,2015-07-09T13:31:43.287,S,2015-07-22T14:39:22.49,"Besvaret, endeligt",2015-04-24T10:40:06.503,§ 20-spørgsmål,2015-05-22T16:22:09.413
4,2,10,11.0,20,"Er ministeren enig i vurderingen af, at grønla...",Om NSA-aflytninger eller aflytninger fra andre...,O,S 725,S,725.0,...,2017-12-05T19:42:22.857,9.0,Relevant for,2015-07-09T13:31:43.287,S,2015-07-22T14:39:22.49,"Besvaret, endeligt",2015-04-24T10:40:06.503,§ 20-spørgsmål,2015-05-22T16:22:09.413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368150,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,14.0,Minister,2015-08-13T10:24:56.373,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368151,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,9.0,Relevant for,2015-07-09T13:31:43.287,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368152,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,6.0,Ministerområde,2015-07-06T15:03:37.307,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368153,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,17.0,Til,2015-07-09T13:49:36.873,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368154,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,10.0,Spørger,2015-06-01T11:33:00.79,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413

In [141]:
'Stemme.json', 'Stemmetype.json'

('Stemme.json', 'Stemmetype.json')

In [142]:
stemme = pd.read_csv(path+files[39])
stemmetype = pd.read_csv(path+files[40])

In [143]:
stemme = stemme.merge(stemmetype, how="left", left_on="typeid", right_on="id").drop("id_y", axis=1).rename(columns={"id_x":"id"})

In [144]:
stemme

,id,typeid,afstemningid,aktørid,opdateringsdato_x,type,opdateringsdato_y
0,1,1,1,158,2014-09-09T09:05:59.653,For,2014-06-24T15:17:12.423
1,2,1,1,71,2014-09-09T09:05:59.653,For,2014-06-24T15:17:12.423
2,3,1,1,50,2014-09-09T09:05:59.653,For,2014-06-24T15:17:12.423
3,4,1,1,49,2014-09-09T09:05:59.653,For,2014-06-24T15:17:12.423
4,5,1,1,183,2014-09-09T09:05:59.653,For,2014-06-24T15:17:12.423
...,...,...,...,...,...,...,...
1459468,1941321,3,8381,18721,2021-10-28T14:45:29.53,Fravær,2014-06-24T15:17:12.423
1459469,1941322,3,8381,18723,2021-10-28T14:45:29.53,Fravær,2014-06-24T15:17:12.423
1459470,1941323,3,8381,18724,2021-10-28T14:45:29.53,Fravær,2014-06-24T15:17:12.423
1459471,1941324,3,8381,18725,2021-10-28T14:45:29.53,Fravær,2014-06-24T15:17:12.423
1459472,1941325,3,8381,18728,2021-10-28T14:45:29.53,Fravær,2014-06-24T15:17:12.423

In [151]:
list(sag.titelkort.values)

['FIU alm. del',
 'FIU alm. del',
 'Om NSA-aflytninger eller aflytninger fra andre interessenter af grønlandske politikere og embedsfolk.',
 'Om NSA-aflytninger eller aflytninger fra andre interessenter af grønlandske politikere og embedsfolk.',
 'Om NSA-aflytninger eller aflytninger fra andre interessenter af grønlandske politikere og embedsfolk.',
 'Om NSA-aflytninger eller aflytninger fra andre interessenter af grønlandske politikere og embedsfolk.',
 'Om NSA-aflytninger eller aflytninger fra andre interessenter af grønlandske politikere og embedsfolk.',
 'Om NSA-aflytninger eller aflytninger fra andre interessenter af grønlandske politikere og embedsfolk.',
 'Om at bortvise elever, der har indtaget ulovlige stoffer.',
 'Om at bortvise elever, der har indtaget ulovlige stoffer.',
 'Om at bortvise elever, der har indtaget ulovlige stoffer.',
 'Om at bortvise elever, der har indtaget ulovlige stoffer.',
 'Om at bortvise elever, der har indtaget ulovlige stoffer.',
 'Forslag til Europa-Parlamentets og Rådets afgørelse om makrofinansiel bistand til Den Tunesiske Republik',
 'Forslag til Europa-Parlamentets og Rådets afgørelse om makrofinansiel bistand til Den Tunesiske Republik',
 'Forslag til Europa-Parlamentets og Rådets afgørelse om makrofinansiel bistand til Den Tunesiske Republik',
 'Forslag til Rådets afgørelse om bemyndigelse af Frankrig til at anvende en reduceret sats for visse indirekte skatter på "traditionel" rom fremstillet i Guadeloupe, Fransk Guyana, Martinique eller Réunion og om ændring af beslutning 2007/659/EF',
 'Forslag til Rådets afgørelse om bemyndigelse af Frankrig til at anvende en reduceret sats for visse indirekte skatter på "traditionel" rom fremstillet i Guadeloupe, Fransk Guyana, Martinique eller Réunion og om ændring af beslutning 2007/659/EF',
 'Forslag til direktiv om uskyldsformodningen og retten til at være til stede under retssagen i straffesager',
 'Forslag til direktiv om uskyldsformodningen og retten til at være til stede under retssagen i straffesager',
 'Forslag til Europa-Parlamentets og Rådets direktiv om retssikkerhedsgarantier for børn, der er mistænkt eller tiltalt i straffesager',
 'Forslag til Europa-Parlamentets og Rådets direktiv om retssikkerhedsgarantier for børn, der er mistænkt eller tiltalt i straffesager',
 'Om digital kommunikation.',
 'Om digital kommunikation.',
 'Om digital kommunikation.',
 'Om digital kommunikation.',
 'Om digital kommunikation.',
 'Om at udbygge Det Centrale Virksomhedsregister.',
 'Om at udbygge Det Centrale Virksomhedsregister.',
 'Om at udbygge Det Centrale Virksomhedsregister.',
 'Om at udbygge Det Centrale Virksomhedsregister.',
 'Om at udbygge Det Centrale Virksomhedsregister.',
 'Forslag til Europa-Parlamentets og Rådets direktiv om foreløbig retshjælp til mistænkte eller tiltalte, der frihedsberøves, og retshjælp i sager angående europæiske arrestordrer',
 'Forslag til Europa-Parlamentets og Rådets direktiv om foreløbig retshjælp til mistænkte eller tiltalte, der frihedsberøves, og retshjælp i sager angående europæiske arrestordrer',
 'Forslag til direktiv om de retlige rammer for toldovertrædelser og -sanktioner',
 'Forslag til direktiv om de retlige rammer for toldovertrædelser og -sanktioner',
 'Forslag til direktiv om de retlige rammer for toldovertrædelser og -sanktioner',
 'Om den palæstinensiske ambassadør i Tjekkiet.',
 'Om den palæstinensiske ambassadør i Tjekkiet.',
 'Om den palæstinensiske ambassadør i Tjekkiet.',
 'Om den palæstinensiske ambassadør i Tjekkiet.',
 'Om den palæstinensiske ambassadør i Tjekkiet.',
 'Om den palæstinensiske ambassadør i Tjekkiet.',
 'Om regeringens udenrigspolitik på narkotikaområdet.',
 'Om regeringens udenrigspolitik på narkotikaområdet.',
 'Om regeringens udenrigspolitik på narkotikaområdet.',
 'Om regeringens udenrigspolitik på narkotikaområdet.',
 'Om regeringens udenrigspolitik på narkotikaområdet.',
 'Om regeringens udenrigspolitik på narkotikaområdet.',
 'Om Norwegian ikke giver kompensation til passagererne ved forsinkelser og aflysninger.',
 'Om Norwegian ikke giver kompensation til passagererne ved forsinkelser og aflysninger.',
 'Om Norwegian ikke giver kompensation til passagererne ved forsinkelser og aflysninger.',
 'Om Norwegian ikke giver kompensation til passagererne ved forsinkelser og aflysninger.',
 'Om Norwegian ikke giver kompensation til passagererne ved forsinkelser og aflysninger.',
 'Om Norwegian ikke giver kompensation til passagererne ved forsinkelser og aflysninger.',
 'Om straffelovens spionageparagraffer. ',
 'Om straffelovens spionageparagraffer. ',
 'Om straffelovens spionageparagraffer. ',
 'Om straffelovens spionageparagraffer. ',
 'Om straffelovens spionageparagraffer. ',
 'Om at nedsætte broafgiften på Storebæltsbroen.',
 'Om at nedsætte broafgiften på Storebæltsbroen.',
 'Om at nedsætte broafgiften på Storebæltsbroen.',
 'Om at nedsætte broafgiften på Storebæltsbroen.',
 'Om at nedsætte broafgiften på Storebæltsbroen.',
 "Der henvises til TV2's artiklel »Patient døde: lægebil skulle takkes« af 3. januar 2014.",
 "Der henvises til TV2's artiklel »Patient døde: lægebil skulle takkes« af 3. januar 2014.",
 "Der henvises til TV2's artiklel »Patient døde: lægebil skulle takkes« af 3. januar 2014.",
 "Der henvises til TV2's artiklel »Patient døde: lægebil skulle takkes« af 3. januar 2014.",
 "Der henvises til TV2's artiklel »Patient døde: lægebil skulle takkes« af 3. januar 2014.",
 'Om broafgiften på Storebæltsbroen.',
 'Om broafgiften på Storebæltsbroen.',
 'Om broafgiften på Storebæltsbroen.',
 'Om broafgiften på Storebæltsbroen.',
 'Om broafgiften på Storebæltsbroen.',
 'Om ghettobebyggelsen på Motalavej i Korsør.',
 'Om ghettobebyggelsen på Motalavej i Korsør.',
 'Om ghettobebyggelsen på Motalavej i Korsør.',
 'Om ghettobebyggelsen på Motalavej i Korsør.',
 'Om ghettobebyggelsen på Motalavej i Korsør.',
 'Om forskere, der nægtes adgang til arkivoplysninger om Den Kolde Krig.',
 'Om forskere, der nægtes adgang til arkivoplysninger om Den Kolde Krig.',
 'Om forskere, der nægtes adgang til arkivoplysninger om Den Kolde Krig.',
 'Om forskere, der nægtes adgang til arkivoplysninger om Den Kolde Krig.',
 'Om forskere, der nægtes adgang til arkivoplysninger om Den Kolde Krig.',
 'Forslag til direktiv om kloning af dyr',
 'Forslag til direktiv om kloning af dyr',
 'Forslag til Rådets direktiv om markedsføring af fødevarer fra dyrekloner',
 'Forslag til Rådets direktiv om markedsføring af fødevarer fra dyrekloner',
 'Om reglerne for »spillerfiskeri« af unge fodboldspillere.',
 'Om reglerne for »spillerfiskeri« af unge fodboldspillere.',
 'Om reglerne for »spillerfiskeri« af unge fodboldspillere.',
 'Om reglerne for »spillerfiskeri« af unge fodboldspillere.',
 'Om reglerne for »spillerfiskeri« af unge fodboldspillere.',
 'Om den negative udvikling i antallet af nyetablerede virksomheder.',
 'Om den negative udvikling i antallet af nyetablerede virksomheder.',
 'Om den negative udvikling i antallet af nyetablerede virksomheder.',
 'Om den negative udvikling i antallet af nyetablerede virksomheder.',
 'Om den negative udvikling i antallet af nyetablerede virksomheder.',
 'Aktstykke om støtte til den 13. genopfyldning af Den afrikanske Udviklingsfond',
 'Aktstykke om støtte til den 13. genopfyldning af Den afrikanske Udviklingsfond',
 'Aktstykke om støtte til den 13. genopfyldning af Den afrikanske Udviklingsfond',
 'Aktstykke om støtte til den 13. genopfyldning af Den afrikanske Udviklingsfond',
 'Forslag til Rådets henstilling om en kvalitetsramme for praktikophold',
 'Forslag til Rådets henstilling om en kvalitetsramme for praktikophold',
 'Forslag til Europa-Parlamentets og Rådets forordning om nye fødevarer',
 'Forslag til Europa-Parlamentets og Rådets forordning om nye fødevarer',
 'Aktstykke om forhøjet tilskud til retshjælpsinstitutioner og Dansk Flygtningehjælp',
 'Aktstykke om forhøjet tilskud til retshjælpsinstitutioner og Dansk Flygtningehjælp',
 'Aktstykke om forhøjet tilskud til retshjælpsinstitutioner og Dansk Flygtningehjælp',
 'Aktstykke om forhøjet tilskud til retshjælpsinstitutioner og Dansk Flygtningehjælp',
 'Aktstykke om forhøjelse af nettodriftsbevillingen med 0,8 mio. kr. til Kofoeds Skole',
 'Aktstykke om forhøjelse af nettodriftsbevillingen med 0,8 mio. kr. til Kofoeds Skole',
 'Aktstykke om forhøjelse af nettodriftsbevillingen med 0,8 mio. kr. til Kofoeds Skole',
 'Aktstykke om forhøjelse af nettodriftsbevillingen med 0,8 mio. kr. til Kofoeds Skole',
 'Aktstykke om forhøjelse af nettodriftsbevilling på 1 mio. kr. vedr. Rådet for Socialt Udsatte',
 'Aktstykke om forhøjelse af nettodriftsbevilling på 1 mio. kr. vedr. Rådet for Socialt Udsatte',
 'Aktstykke om forhøjelse af nettodriftsbevilling på 1 mio. kr. vedr. Rådet for Socialt Udsatte',
 'Aktstykke om forhøjelse af nettodriftsbevilling på 1 mio. kr. vedr. Rådet for Socialt Udsatte',
 'Forslag til Europa-Parlamentets og Rådets direktiv om begrænsning af visse luftforurenende emissioner fra mellemstore fyringsanlæg',
 'Forslag til Europa-Parlamentets og Rådets direktiv om begrænsning af visse luftforurenende emissioner fra mellemstore fyringsanlæg',
 'Om etablering af en station i Holeby.',
 'Om etablering af en station i Holeby.',
 'Om etablering af en station i Holeby.',
 'Om etablering af en station i Holeby.',
 'Om etablering af en station i Holeby.',
 'Forslag til direktiv om nedbringelse af nationale emissioner af luftforurenende stoffer NEC-direktivet)',
 'Forslag til direktiv om nedbringelse af nationale emissioner af luftforurenende stoffer NEC-direktivet)',
 'Om ISDS-ordningen.',
 'Om ISDS-ordningen.',
 'Om ISDS-ordningen.',
 'Om ISDS-ordningen.',
 'Om ISDS-ordningen.',
 'Om ISDS-ordningen.',
 'Om Norwegians ansøgning om at flyve mellem lufthavne i Europa og USA.',
 'Om Norwegians ansøgning om at flyve mellem lufthavne i Europa og USA.',
 'Om Norwegians ansøgning om at flyve mellem lufthavne i Europa og USA.',
 'Om Norwegians ansøgning om at flyve mellem lufthavne i Europa og USA.',
 'Om Norwegians ansøgning om at flyve mellem lufthavne i Europa og USA.',
 'Om Norwegians ansøgning om at flyve mellem lufthavne i Europa og USA.',
 'Om politirazziaer over for udenlandske prostituerede.',
 'Om politirazziaer over for udenlandske prostituerede.',
 'Om politirazziaer over for udenlandske prostituerede.',
 'Om politirazziaer over for udenlandske prostituerede.',
 'Om politirazziaer over for udenlandske prostituerede.',
 'Om menneskehandel.',
 'Om menneskehandel.',
 'Om menneskehandel.',
 'Om menneskehandel.',
 'Om menneskehandel.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om brug af elektronisk fodlænke på kriminelle på tålt ophold.',
 'Om at give udgang til indsatte indbrudstyve i juledagene.',
 'Om at give udgang til indsatte indbrudstyve i juledagene.',
 'Om at give udgang til indsatte indbrudstyve i juledagene.',
 'Om at give udgang til indsatte indbrudstyve i juledagene.',
 'Om at give udgang til indsatte indbrudstyve i juledagene.',
 'Rådsmøde udenrigsanl. 20/1-14',
 'Forslag til Rådets afgørelse om ændring af beslutning 2009/831/EF for så vidt angår dens anvendelsesperiode',
 'Forslag til Rådets afgørelse om ændring af beslutning 2009/831/EF for så vidt angår dens anvendelsesperiode',
 'Om rapporten »A Transatlantic Corporate Bill of Rights«.',
 'Om rapporten »A Transatlantic Corporate Bill of Rights«.',
 'Om rapporten »A Transatlantic Corporate Bill of Rights«.',
 'Om rapporten »A Transatlantic Corporate Bill of Rights«.',
 'Om rapporten »A Transatlantic Corporate Bill of Rights«.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om »Fair Løsning« er fuldt finansieret.',
 'Om den økonomiske plan »Fair Løsning«.',
 'Om den økonomiske plan »Fair Løsning«.',
 'Om den økonomiske plan »Fair Løsning«.',
 'Om den økonomiske plan »Fair Løsning«.',
 'Om den økonomiske plan »Fair Løsning«.',
 'Om den økonomiske plan »Fair Løsning«.',
 'Om vurdering af »Fair Løsning«.',
 'Om vurdering af »Fair Løsning«.',
 'Om vurdering af »Fair Løsning«.',
 'Om vurdering af »Fair Løsning«.',
 'Om vurdering af »Fair Løsning«.',
 'Om vurdering af »Fair Løsning«.',
 'Om implementering af »Fair Løsning«.',
 'Om implementering af »Fair Løsning«.',
 'Om implementering af »Fair Løsning«.',
 'Om implementering af »Fair Løsning«.',
 'Om implementering af »Fair Løsning«.',
 'Om implementering af »Fair Løsning«.',
 'Om loft over antallet af interne møder i det offentlige.',
 'Om loft over antallet af interne møder i det offentlige.',
 'Om loft over antallet af interne møder i det offentlige.',
 'Om loft over antallet af interne møder i det offentlige.',
 'Om loft over antallet af interne møder i det offentlige.',
 'Om loft over antallet af interne møder i det offentlige.',
 'Om hashhandel på en villavej i Vejle.',
 'Om hashhandel på en villavej i Vejle.',
 'Om hashhandel på en villavej i Vejle.',
 'Om hashhandel på en villavej i Vejle.',
 'Om hashhandel på en villavej i Vejle.',
 'Om forhøjede bidragssatser og kursskæring på ejendomslån.',
 'Om forhøjede bidragssatser og kursskæring på ejendomslån.',
 'Om forhøjede bidragssatser og kursskæring på ejendomslån.',
 'Om forhøjede bidragssatser og kursskæring på ejendomslån.',
 'Om forhøjede bidragssatser og kursskæring på ejendomslån.',
 'Meddelelse fra Kommissionen til Europa-Parlamentet, Rådet, Det Europæiske Økonomiske og Sociale Udvalg og Regionsudvalget – En ny EU-skovstrategi: for skove og den skovbaserede sektor',
 'Meddelelse fra Kommissionen til Europa-Parlamentet, Rådet, Det Europæiske Økonomiske og Sociale Udvalg og Regionsudvalget – En ny EU-skovstrategi: for skove og den skovbaserede sektor',
 'Meddelelse fra Kommissionen til Europa-Parlamentet, Rådet, Det Europæiske Økonomiske og Sociale Udvalg og Regionsudvalget – En ny EU-skovstrategi: for skove og den skovbaserede sektor',
 'Om pensionister, der nægtes lån.',
 'Om pensionister, der nægtes lån.',
 'Om pensionister, der nægtes lån.',
 'Om pensionister, der nægtes lån.',
 'Om pensionister, der nægtes lån.',
 'Om synlige identifikationsnumre på polititjenestemænds uniformer.',
 'Om synlige identifikationsnumre på polititjenestemænds uniformer.',
 'Om synlige identifikationsnumre på polititjenestemænds uniformer.',
 'Om synlige identifikationsnumre på polititjenestemænds uniformer.',
 'Om synlige identifikationsnumre på polititjenestemænds uniformer.',
 'Om personlige og materielle konsekvenser af stormfloden.',
 'Om personlige og materielle konsekvenser af stormfloden.',
 'Om personlige og materielle konsekvenser af stormfloden.',
 'Om personlige og materielle konsekvenser af stormfloden.',
 'Om personlige og materielle konsekvenser af stormfloden.',
 'Om at utilpassede unge indvandrerdrenge flere steder i landet driver gæk med politiet og lovlydige borgere.',
 'Om at utilpassede unge indvandrerdrenge flere steder i landet driver gæk med politiet og lovlydige borgere.',
 'Om at utilpassede unge indvandrerdrenge flere steder i landet driver gæk med politiet og lovlydige borgere.',
 'Om at utilpassede unge indvandrerdrenge flere steder i landet driver gæk med politiet og lovlydige borgere.',
 'Om at utilpassede unge indvandrerdrenge flere steder i landet driver gæk med politiet og lovlydige borgere.',
 'Om at utilpassede unge indvandrerdrenge flere steder i landet driver gæk med politiet og lovlydige borgere.',
 'Om antallet af lommetyverier.',
 'Om antallet af lommetyverier.',
 'Om antallet af lommetyverier.',
 'Om antallet af lommetyverier.',
 'Om antallet af lommetyverier.',
 'Om antallet af lommetyverier.',
 'Om lystbådehavne.',
 'Om lystbådehavne.',
 'Om lystbådehavne.',
 'Om lystbådehavne.',
 'Om lystbådehavne.',
 'Om stormen Bodils hærgen i lystbådehavne.',
 'Om stormen Bodils hærgen i lystbådehavne.',
 'Om stormen Bodils hærgen i lystbådehavne.',
 'Om stormen Bodils hærgen i lystbådehavne.',
 'Om stormen Bodils hærgen i lystbådehavne.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om varigheden af tidsbegrænsede opholdstilladelser.',
 'Om utilpassede unge, der generer borgere og psykisk syge på Motalavej i Korsør.',
 'Om utilpassede unge, der generer borgere og psykisk syge på Motalavej i Korsør.',
 'Om utilpassede unge, der generer borgere og psykisk syge på Motalavej i Korsør.',
 'Om utilpassede unge, der generer borgere og psykisk syge på Motalavej i Korsør.',
 'Om utilpassede unge, der generer borgere og psykisk syge på Motalavej i Korsør.',
 'Om utilpassede unge, der generer borgere og institutioner.',
 'Om utilpassede unge, der generer borgere og institutioner.',
 'Om utilpassede unge, der generer borgere og institutioner.',
 'Om utilpassede unge, der generer borgere og institutioner.',
 'Om utilpassede unge, der generer borgere og institutioner.',
 'Om udvidelsen af ghettokriterierne',
 'Om udvidelsen af ghettokriterierne',
 'Om udvidelsen af ghettokriterierne',
 'Om udvidelsen af ghettokriterierne',
 'Om udvidelsen af ghettokriterierne',
 'Om ghettoproblemer i et boligområde.',
 'Om ghettoproblemer i et boligområde.',
 'Om ghettoproblemer i et boligområde.',
 'Om ghettoproblemer i et boligområde.',
 'Om ghettoproblemer i et boligområde.',
 'Tidligere fortroligt aktstykke om dansk genindtræden i NATO Alliance Ground Surveillance program',
 'Tidligere fortroligt aktstykke om dansk genindtræden i NATO Alliance Ground Surveillance program',
 'Tidligere fortroligt aktstykke om dansk genindtræden i NATO Alliance Ground Surveillance program',
 'Tidligere fortroligt aktstykke om dansk genindtræden i NATO Alliance Ground Surveillance program',
 'Tidligere fortroligt aktstykke om anskaffelse af personlige radioer (Personel Role Radio)',
 'Tidligere fortroligt aktstykke om anskaffelse af personlige radioer (Personel Role Radio)',
 'Tidligere fortroligt aktstykke om anskaffelse af personlige radioer (Personel Role Radio)',
 'Tidligere fortroligt aktstykke om anskaffelse af personlige radioer (Personel Role Radio)',
 'Om tillægsbevillingsloven for finansåret 2013.',
 'Om tillægsbevillingsloven for finansåret 2013.',
 'Om tillægsbevillingsloven for finansåret 2013.',
 'Om tillægsbevillingsloven for finansåret 2013.',
 'Om adgang til arkivoplysninger om Danmark under den kolde krig.',
 'Om adgang til arkivoplysninger om Danmark under den kolde krig.',
 'Om adgang til arkivoplysninger om Danmark under den kolde krig.',
 'Om adgang til arkivoplysninger om Danmark under den kolde krig.',
 'Om adgang til arkivoplysninger om Danmark under den kolde krig.',
 'Om tildeling af nyt personnummer i særlige tilfælde.',
 'Om tildeling af nyt personnummer i særlige tilfælde.',
 'Om tildeling af nyt personnummer i særlige tilfælde.',
 'Om tildeling af nyt personnummer i særlige tilfælde.',

In [152]:
sag

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,opdateringsdato_y,rolleid,rolle,opdateringsdato_x,kategori,opdateringsdato_y,status,opdateringsdato_x,type,opdateringsdato_y
0,1,4,2.0,8,FIU alm. del,FIU alm. del,O,NaN,NaN,NaN,...,2015-06-23T10:32:14.607,9.0,Relevant for,2015-07-09T13:31:43.287,Alm. del,2015-08-13T10:24:56.373,Igangværende,2015-05-21T11:51:26.38,Alm. del,2015-08-13T10:24:56.373
1,1,4,2.0,8,FIU alm. del,FIU alm. del,O,NaN,NaN,NaN,...,2015-06-23T10:32:14.607,6.0,Ministerområde,2015-07-06T15:03:37.307,Alm. del,2015-08-13T10:24:56.373,Igangværende,2015-05-21T11:51:26.38,Alm. del,2015-08-13T10:24:56.373
2,2,10,11.0,20,"Er ministeren enig i vurderingen af, at grønla...",Om NSA-aflytninger eller aflytninger fra andre...,O,S 725,S,725.0,...,2017-12-05T19:42:22.857,14.0,Minister,2015-08-13T10:24:56.373,S,2015-07-22T14:39:22.49,"Besvaret, endeligt",2015-04-24T10:40:06.503,§ 20-spørgsmål,2015-05-22T16:22:09.413
3,2,10,11.0,20,"Er ministeren enig i vurderingen af, at grønla...",Om NSA-aflytninger eller aflytninger fra andre...,O,S 725,S,725.0,...,2017-12-05T19:42:22.857,9.0,Relevant for,2015-07-09T13:31:43.287,S,2015-07-22T14:39:22.49,"Besvaret, endeligt",2015-04-24T10:40:06.503,§ 20-spørgsmål,2015-05-22T16:22:09.413
4,2,10,11.0,20,"Er ministeren enig i vurderingen af, at grønla...",Om NSA-aflytninger eller aflytninger fra andre...,O,S 725,S,725.0,...,2017-12-05T19:42:22.857,9.0,Relevant for,2015-07-09T13:31:43.287,S,2015-07-22T14:39:22.49,"Besvaret, endeligt",2015-04-24T10:40:06.503,§ 20-spørgsmål,2015-05-22T16:22:09.413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368150,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,14.0,Minister,2015-08-13T10:24:56.373,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368151,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,9.0,Relevant for,2015-07-09T13:31:43.287,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368152,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,6.0,Ministerområde,2015-07-06T15:03:37.307,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368153,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,17.0,Til,2015-07-09T13:49:36.873,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413
368154,89872,10,11.0,22,Hvad er ministerens holdning til sagen om den ...,Om SU.,O,S 79,S,79.0,...,2021-10-12T16:32:24.917,10.0,Spørger,2015-06-01T11:33:00.79,S,2015-07-22T14:39:22.49,Anmeldt,2015-07-09T14:29:01.24,§ 20-spørgsmål,2015-05-22T16:22:09.413

In [153]:
dagsordenspunktsag

         id  dagsordenspunktid  sagid          opdateringsdato
0         3                101   6900  2014-09-16T15:57:33.623
1         4                100    648  2014-09-16T15:57:33.623
2         6                102   6901  2014-09-16T15:57:33.623
3         7                103   6902  2014-09-16T15:57:33.623
4        11               3748   2230  2014-09-19T14:23:57.567
...     ...                ...    ...                      ...
5854  29529              71747  89758  2021-10-12T09:21:29.947
5855  29530              71890  89758   2021-10-12T09:21:29.96
5856  29531              71768  89749   2021-10-12T09:26:28.71
5857  29532              71892  89619  2021-10-12T10:04:38.157
5858  29533              71605  89619  2021-10-12T10:04:38.157

[5859 rows x 4 columns]

In [154]:
dagsordenspunkt

,id,kørebemærkning,titel,kommentar,nummer,forhandlingskode,forhandling,superid,sagstrinid,mødeid,offentlighedskode,opdateringsdato
0,1,NaN,Drøftelse og afgivelse af tilsynets årlige ber...,NaN,1,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
1,2,NaN,Drøftelse af svar fra Region Sjælland vedr. ti...,NaN,2,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
2,3,NaN,Drøftelse af evalueringen af ordningen med tvu...,NaN,3,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
3,4,NaN,Svar vedr. hvilke regler der gælder for tvangs...,NaN,4,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
4,5,NaN,"Svar vedr. en nærmere redegørelse for, hvilke ...",NaN,5,NaN,NaN,NaN,NaN,4,O,2014-11-12T09:11:53.447
...,...,...,...,...,...,...,...,...,...,...,...,...
26028,71888,NaN,Eventuelt.,NaN,4,NaN,NaN,NaN,NaN,11979,O,2021-10-11T16:19:42.723
26029,71889,NaN,Modtagelse af deputation fra:,NaN,2,NaN,NaN,NaN,NaN,11942,O,2021-10-12T09:21:29.947
26030,71890,NaN,Tivoliforeningen vedr. støtte til de omrejsend...,NaN,a,NaN,NaN,NaN,230103.0,11942,O,2021-10-12T09:21:29.96
26031,71891,NaN,Modtagelse af deputation fra:,NaN,1,NaN,NaN,NaN,NaN,11945,O,2021-10-12T10:04:38.157
26032,71892,NaN,Præsteforeningen m.fl. vedr. nedlæggelse af Pe...,NaN,a,NaN,NaN,NaN,230104.0,11945,O,2021-10-12T10:04:38.157

In [162]:
len(set(sag.titelkort)), len(set(sag.titel))

(70015, 82414)

In [165]:
dagsordenspunkt.titel.values

array(['Drøftelse og afgivelse af tilsynets årlige beretning – jf. § 71 alm. del - bilag 94 (internt).',
       'Drøftelse af svar fra Region Sjælland vedr. tilsynsbesøg den 14. marts 2014 på Afdeling for Børne- og ungepsykiatri i Roskilde, jf. § 71 alm. del - bilag 91 (internt).',
       'Drøftelse af evalueringen af ordningen med tvungen opfølgning, jf. § 71 alm. del - bilag 90.',
       ...,
       'Tivoliforeningen vedr. støtte til de omrejsende tivolier og cirkusser i vinterperioden, så de kan klare sig frem til sæsonåbning til foråret, jf. KUU alm. del – bilag 5',
       'Modtagelse af deputation fra:',
       'Præsteforeningen m.fl. vedr. nedlæggelse af Pensionskassen af 1950, jf. KIU alm. del - bilag 3'],
      dtype=object)

In [170]:
forslag.titel.values

array(['Aktstykke om støtte til den 13. genopfyldning af Den afrikanske Udviklingsfond',
       'Aktstykke om forhøjet tilskud til retshjælpsinstitutioner og Dansk Flygtningehjælp',
       'Aktstykke om forhøjelse af nettodriftsbevillingen med 0,8 mio. kr. til Kofoeds Skole',
       ...,
       'Aktstykke om støtte til Nordic Sugar mhp. højere miljøbeskyttelsesniveau',
       'Aktstykke om etablering af ladestandere i boligforeninger.',
       'Aktstykke om tilskud til 2030-Panelet.'], dtype=object)

In [172]:
aktstykke.titel.values

array(['Forslag til lov om tillægsbevilling for finansåret 2013.',
       'Forslag til lov om ændring af lov om Det Centrale Personregister. (Tildeling af nyt personnummer i særlige tilfælde i forbindelse med identitetsmisbrug samt ophævelse af markeringer i CPR om forskerbeskyttelse).',
       'Forslag til lov om Danmarks Innovationsfond.', ...,
       'Forslag til lov om ændring af lov om luftfart. (Præcisering af rammerne for indskrænkninger i adgangen til luftfart og for tildeling af tilladelse til at udføre ruteflyvning, hjemmel til krav om sikkerhedsgodkendelser m.v.).',
       'Forslag til lov om ændring af færdselsloven og lov om produkter og markedsovervågning. (Markedsovervågning på færdselsområdet m.v.).',
       'Forslag til lov om ændring af jernbaneloven, lov om elektrificering af jernbanen og ligningsloven. (Fravigelse af støjkrav i forbindelse med jernbaneprojekter i særlige tilfælde og kompensation herfor).'],
      dtype=object)

In [173]:
aktstykke

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,paragrafnummer,paragraf,afgørelsesdato,afgørelse,rådsmødedato,lovnummer,lovnummerdato,retsinformationsurl,fremsatundersagid,deltundersagid
0,66,3,13,11,Forslag til lov om tillægsbevilling for finans...,Om tillægsbevillingsloven for finansåret 2013.,O,L 105,L,105,...,NaN,NaN,NaN,NaN,NaN,1,2014-03-18T00:00:00,NaN,NaN,NaN
1,68,3,13,11,Forslag til lov om ændring af lov om Det Centr...,Om tildeling af nyt personnummer i særlige til...,O,L 110,L,110,...,NaN,NaN,NaN,NaN,NaN,311,2014-03-29T00:00:00,NaN,NaN,NaN
2,69,3,13,11,Forslag til lov om Danmarks Innovationsfond.,Om Danmarks Innovationsfond.,O,L 107,L,107,...,NaN,NaN,NaN,NaN,NaN,306,2014-03-29T00:00:00,NaN,NaN,NaN
3,70,3,13,11,Forslag til lov om ændring af lov om forskning...,Om konsekvensændringer som følge af lov om Dan...,O,L 109,L,109,...,NaN,NaN,NaN,NaN,NaN,310,2014-03-29T00:00:00,NaN,NaN,NaN
4,71,3,13,11,Forslag til lov om ændring af lov om teknologi...,Om konsekvensændringer som følge af lov om Dan...,O,L 108,L,108,...,NaN,NaN,NaN,NaN,NaN,309,2014-03-29T00:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4194,89665,3,13,25,Forslag til lov om ændring af taxiloven. (Doku...,Om justering af taxiloven.,O,L 19,L,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4195,89666,3,13,25,Forslag til lov om ændring af lov om fødevarer...,Om datadrevet kontrol og offentliggørelse af k...,O,L 40,L,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4196,89667,3,13,25,Forslag til lov om ændring af lov om luftfart....,Om rammerne for indskrænkninger i adgangen til...,O,L 20,L,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4197,89668,3,13,25,Forslag til lov om ændring af færdselsloven og...,Om markedsovervågning på færdselsområdet m.v.,O,L 21,L,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4198,89669,3,13,25,"Forslag til lov om ændring af jernbaneloven, l...",Om fravigelse af støjkrav i forbindelse med je...,O,L 22,L,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [174]:
sagdokument

,id,sagid,dokumentid,bilagsnummer,frigivelsesdato,opdateringsdato_x,rolleid,rolle,opdateringsdato_y
0,21,4496,7913,NaN,2013-10-16T14:54:51,2014-09-16T06:16:53.99,4,Hovedtilknytning,2015-07-15T09:44:04.857
1,30,4886,8595,NaN,2013-11-20T13:40:45,2014-09-14T06:18:43.64,4,Hovedtilknytning,2015-07-15T09:44:04.857
2,55,4262,7515,NaN,2013-10-01T15:51:19,2014-09-14T03:18:42.27,4,Hovedtilknytning,2015-07-15T09:44:04.857
3,84,5063,8896,NaN,2013-12-02T11:05:42,2014-09-14T07:18:11.007,4,Hovedtilknytning,2015-07-15T09:44:04.857
4,87,4680,8245,NaN,2013-11-01T10:29:01,2014-09-14T05:19:24.097,4,Hovedtilknytning,2015-07-15T09:44:04.857
...,...,...,...,...,...,...,...,...,...
536579,1225576,89605,949213,Spørgsmål 129,2021-11-04T00:00:00,2021-11-04T15:49:16.647,4,Hovedtilknytning,2015-07-15T09:44:04.857
536580,1225577,89755,949214,Spørgsmål 179,2021-11-04T00:00:00,2021-11-04T15:50:10.537,4,Hovedtilknytning,2015-07-15T09:44:04.857
536581,1225578,89755,949215,Spørgsmål 180,2021-11-04T00:00:00,2021-11-04T15:50:45.377,4,Hovedtilknytning,2015-07-15T09:44:04.857
536582,1225579,89755,949216,Spørgsmål 181,2021-11-04T00:00:00,2021-11-04T15:51:48.46,4,Hovedtilknytning,2015-07-15T09:44:04.857
536583,1225580,89755,949219,Spørgsmål 182,2021-11-04T00:00:00,2021-11-04T15:55:41.23,4,Hovedtilknytning,2015-07-15T09:44:04.857

In [177]:
debat

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,paragrafnummer,paragraf,afgørelsesdato,afgørelse,rådsmødedato,lovnummer,lovnummerdato,retsinformationsurl,fremsatundersagid,deltundersagid
0,40,6,NaN,54,Rådsmøde nr. 3288 (udenrigsanliggender) den 20...,Rådsmøde udenrigsanl. 20/1-14,O,Rådsmøde 3288 - Udenrigsanl.,NaN,NaN,...,NaN,NaN,NaN,NaN,2014-01-20T00:00:00,NaN,NaN,NaN,NaN,NaN
1,80,11,NaN,5,Udenrigsministerens sikkerhedspolitiske redegø...,Om den sikkerhedspolitiske redegørelse 2013.,O,R 7,R,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,102,11,NaN,5,Udenrigsministerens redegørelse om Europarådet...,Om Europarådets virksomhed og Danmarks deltage...,O,R 8,R,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,105,6,NaN,54,Rådsmøde nr. 3290 (økonomi og finans) den 28. ...,Rådsmøde økofin 28/1-14,O,Rådsmøde 3290 - Økofin,NaN,NaN,...,NaN,NaN,NaN,NaN,2014-01-28T00:00:00,NaN,NaN,NaN,NaN,NaN
4,168,6,NaN,54,Det Europæiske Råd den 20.-21. marts 2014,Det Europæiske Råd 20-21/3-14,O,Det Europæiske Råd 20-21/3-14,NaN,NaN,...,NaN,NaN,NaN,NaN,2014-03-20T00:00:00,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2412,89782,6,21.0,54,Rådsmøde (udenrigsanliggender) den 18. oktober...,Rådsmøde udenrigsanliggender 18/10-21,O,Rådsmøde 18/10-21 - Udenrigsanliggender,NaN,NaN,...,NaN,NaN,NaN,NaN,2021-10-18T00:00:00,NaN,NaN,NaN,NaN,NaN
2413,89783,6,28.0,54,Rådsmøde (almindelige anliggender) den 19. okt...,Rådsmøde almindelige anliggender 19/10-21,O,Rådsmøde 19/10-21- almindelige anliggender,NaN,NaN,...,NaN,NaN,NaN,NaN,2021-10-19T00:00:00,NaN,NaN,NaN,NaN,NaN
2414,89807,6,21.0,54,Videokonference (udenrigsanliggender - udvikli...,Videokonference udviklingsministre 11/10-21,O,Videokonference 11/10-21 - udenrigsanliggender,NaN,NaN,...,NaN,NaN,NaN,NaN,2021-10-11T17:30:00,NaN,NaN,NaN,NaN,NaN
2415,89808,6,30.0,54,Uformel videokonference telekommunikationsmini...,Videokonference telekommunikation 14/10-21,O,"Videokonf. 14/10-21 - transport, tele og energi",NaN,NaN,...,NaN,NaN,NaN,NaN,2021-10-14T17:00:00,NaN,NaN,NaN,NaN,NaN
2416,89843,6,24.0,54,Videokonference for EU's økonomi- og finansmin...,Videokonference for EU's økonomi- og finansmin...,O,Videokonference 28/10-21 - økofin,NaN,NaN,...,NaN,NaN,NaN,NaN,2021-10-28T00:00:00,NaN,NaN,NaN,NaN,NaN

,id,typeid,kategoriid,statusid,titel,titelkort,offentlighedskode,nummer,nummerprefix,nummernumerisk,...,paragrafnummer,paragraf,afgørelsesdato,afgørelse,rådsmødedato,lovnummer,lovnummerdato,retsinformationsurl,fremsatundersagid,deltundersagid
0,7337,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7338,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7339,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7344,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,35738,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,44548,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,52305,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,52787,1,NaN,1,UPN UM-del,UPN UM-del,O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [181]:
periode

,id,startdato,slutdato,type,kode,titel,opdateringsdato
0,1,1995-01-01T00:00:00,1995-12-31T00:00:00,finans,19951,1995,2014-08-11T12:51:35
1,2,1996-01-01T12:00:00,1996-12-31T12:00:00,finans,19961,1996,2014-08-11T12:51:35
2,3,2002-01-01T00:00:00,2002-12-31T00:00:00,finans,20021,2002,2014-08-11T12:51:35
3,4,2003-01-01T00:00:00,2003-12-31T00:00:00,finans,20031,2003,2014-08-11T12:51:35
4,5,2004-01-01T00:00:00,2004-12-31T00:00:00,finans,20041,2004,2014-08-11T12:51:35
...,...,...,...,...,...,...,...
146,151,2019-10-01T12:00:00,2020-10-06T12:00:00,samling,20191,2019-20,2019-09-09T12:29:48.397
147,152,2020-01-01T12:00:00,2020-12-31T12:00:00,finans,20201,2020,2019-12-18T16:48:20.937
148,153,2020-10-06T12:00:00,2021-10-05T12:00:00,samling,20201,2020-21,2020-10-01T16:07:28.523
149,154,2020-01-01T12:00:00,2021-12-31T12:00:00,finans,20211,2021,2021-03-01T13:00:08.27
150,155,2021-10-05T12:00:00,2022-10-04T12:00:00,samling,20211,2021-22,2021-09-08T13:15:06.07